### ISSUE TITLE
Questions about xxxStorageLocation syntax

### ISSUE THREAD

**Issue by DracoYan-111** [OpenZeppelin/openzeppelin-upgrades#1000]
Why is this writing method used in the new version of the contract? What are the benefits of this writing method? Is there any document that I can refer to?

`
struct ERC2981Storage {
        RoyaltyInfo _defaultRoyaltyInfo;
        mapping(uint256 tokenId => RoyaltyInfo) _tokenRoyaltyInfo;
    }
    // keccak256(abi.encode(uint256(keccak256("openzeppelin.storage.ERC2981")) - 1)) & ~bytes32(uint256(0xff))
    bytes32 private constant ERC2981StorageLocation = 0xdaedc9ab023613a7caf35e703657e986ccfad7e3eb0af93a2853f8d65dd86b00;
`

**Comment by ericglau** [comment]
That is using the [ERC-7201: Namespaced Storage Layout](https://eips.ethereum.org/EIPS/eip-7201) pattern, which was introduced starting from version 5.0.0 of the [upgradeable variant of OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/).  [This blog post](https://blog.openzeppelin.com/introducing-openzeppelin-contracts-5.0#Namespaced) outlines its benefits.

If you have further questions on this pattern, feel free to post on our forum at https://forum.openzeppelin.com/
