### ISSUE TITLE
hardhat-upgrades causes compilation to always start from scratch for zksync

### ISSUE THREAD

**Issue by novaknole** [OpenZeppelin/openzeppelin-upgrades#1012]
I'm using this package inside my `hardhat.config.ts` as:

```js
import '@openzeppelin/hardhat-upgrades';
```

Everything was working fine, but today, I added the support of zksolc compiler inside hardhat settings. The interesting thing is that if the above import is NOT commented, the following occurs:
1. I try to compile contracts with zksync. Compilation works.
2. if I re-run the compilation, it starts to compile them again from scratch.

If I comment out the above import, then:
1. I try to compile contracts with zksync. Compilation works.
2. if I re-run the compilation, it does NOT recompile the contracts.

What does `hardhat-upgrades` does that causes such behaviour ? I am using `1.23.1` version and latest version fails as well.

**Comment by ericglau** [comment]
For zkSync, you may need to use https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-upgradable.html

**Comment by ericglau** [comment]
Closing as per the above comment.
