### ISSUE TITLE
implementation contract not verified on etherscan after deployment

### ISSUE THREAD

**Issue by SvenMeyer** [OpenZeppelin/openzeppelin-upgrades#1018]
I just deployed an upgradeable NFT contract using a small script 

```
  const DDC_FACTORY = (await ethers.getContractFactory("DDC")) as unknown as DDC__factory;

  const ddc = (await upgrades.deployProxy(DDC_FACTORY, [
    await admin.getAddress(),
    await minter.getAddress(),
    await admin.getAddress(),
  ])) as unknown as DDC; // workaround until this is fixed : https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/535

  await ddc.waitForDeployment();

  console.log("DDC deployed to:", await ddc.getAddress());
```

which I called to deploy the contract on Sepolia
`npx hardhat --network sepolia run scripts/create-ddc.ts`

I can see the verified contract here :
https://sepolia.etherscan.io/address/0xadbEA6D2B0344F7F480B15343BB46f4dbFf648E7#code

but not the option to treat it like a contract with a proxy

If I chose [More Options] [Is this a proxy] [Verify]

I get the error message 
```
The proxy contract verification completed with the message:

The implementation contract at [0x275eaf53fb1d9a6764e19bd7ae3908345f015f31](https://sepolia.etherscan.io/address/0x275eaf53fb1d9a6764e19bd7ae3908345f015f31#code) does not seem to be verified.
Please verify and publish the contract source before proceeding with this proxy verification.
```

Shouldn't the implementation source code be uploaded and verified as well after deployment ?

**Comment by rsimonton** [comment]
It's not automatic, you need to verify it in your script.  Take a look at https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify

**Comment by ericglau** [comment]
See the steps at https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#verify to use `hardhat verify` to fully verify the proxy, which will include the implementation.

**Comment by SvenMeyer** [comment]
@rsimonton @ericglau Thanks for your instant feedback.
I thought that I had read "somewhere" that verification for the proxy and implementation would be included in `upgrades.deployProxy`.

Anyway, it works as you suggested. I am just surprised to not see any methods to call for the proxy and my question would be what function to call on the proxy to get the implementation address ? :thinking: 

https://sepolia.etherscan.io/address/0xadbEA6D2B0344F7F480B15343BB46f4dbFf648E7#readContract
