### ISSUE TITLE
Defender DeployProxy not working when using `constructorArgs`

### ISSUE THREAD

**Issue by lucasmarambio** [OpenZeppelin/openzeppelin-upgrades#1026]
Trying to deploy an UUPS upgradeable proxy through Defender where the implementation contract has a constructor identified with `@custom:oz-upgrades-unsafe-allow`, throws the following error:

![image](https://github.com/OpenZeppelin/openzeppelin-upgrades/assets/9018508/a8fe49a6-83bf-4d7f-bfca-bc4e9228d7aa)

I tried to do this deployment without Defender and it works fine, but as I want to include this deployment behind an approval process mechanism, I'm trying to deploy it using Defender. Bear in mind that on my constructor I've a param requirement, so I have to execute the deployment using the following code:

```typescript
const proxy = await defender
    .deployProxy(factory, [upgradeApprovalProcess.address], {
        initializer: "initialize",
        kind: "uups",
        constructorArgs: [FORWARDER_ADDRESS],
        salt,
      })
    .then(async (f) => await f.waitForDeployment());
```

Behind the scenes it seems that [defenderDeploy](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/utils/deploy.ts#L18C1-L24C49) and [ethersDeploy](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/utils/deploy.ts#L24) have a difference that makes me to have a successful work when using the second one. Apparently, [defenderDeploy is overriding the `constructorArgs` required by the proxy deployment with the `constructorArgs`](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/defender/deploy.ts#L66C60-L66C88) that were used for the implementation deploy and causing the issue.

Just in case, on my constructor I'm sending the address of an [upgradeable forwarder](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/metatx/ERC2771ForwarderUpgradeable.sol) that I use to relay transactions.

**Any workaround for this scenario?**

**Comment by ericglau** [comment]
Thanks for reporting, this is fixed in [@openzeppelin/hardhat-upgrades@3.1.1](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%403.1.1)
