### ISSUE TITLE
InvalidDeployment Error (Removed from manifest)

### ISSUE THREAD

**Issue by 0xSunshine** [OpenZeppelin/openzeppelin-upgrades#1027]
Hello @ericglau,

We are having an issue with @openzeppelin/hardhat-upgrades ` when deploying multiple instances of same proxy factory, specifically `hardhat.upgrades.deployProxy() will throw with `InvalidDeployment [Error]: No contract at address 0x... (Removed from manifest)`

Can the deployment metadata files in `.openzeppelin` be renamed safely or saved with aliases to differentiate instances and avoid these conflicts?

**Comment by ericglau** [comment]
Hi @0xSunshine, can you provide more details on what you are trying to do?  What do you mean by multiple instances of same proxy factory?

If you want to use a different network files directory for certain scenarios, see https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files#custom-network-files-location

**Comment by 0xSunshine** [comment]
> Hi @0xSunshine, can you provide more details on what you are trying to do? What do you mean by multiple instances of same proxy factory?
> 
> If you want to use a different network files directory for certain scenarios, see https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files#custom-network-files-location

hello, I meant deploying a proxy instance (not impl) on multiple networks, and yes I found `MANIFEST_DEFAULT_DIR ` to be just what i needed. Thank you

**Comment by ericglau** [comment]
If deploying the proxy on different networks with different chain ids, there shouldn't be any conflicts since the plugin creates a different network file for each network.

But if you are using multiple networks with the same chain id, then yes you would need to do as above.

**Comment by 0xSunshine** [comment]
> If deploying the proxy on different networks with different chain ids, there shouldn't be any conflicts since the plugin creates a different network file for each network.
> 
> But if you are using multiple networks with the same chain id, then yes you would need to do as above.

no my case was about reusing multiple proxies-impl pairs in the same network. Would be nice to add an alias label to differentiate deployments within the same network.

**Comment by ericglau** [comment]
Can you give a concrete example of what you want to achieve, and why it does not currently work?

**Comment by 0xSunshine** [comment]
> Can you give a concrete example of what you want to achieve, and why it does not currently work? Thanks.

Right now, if I use deployProxy more than once for the same factory name (in my example below, let's say to deploy multiple oracles), I have no way to re-use them and/or distinguish among such deployments (?). In this case, deployProxy could have an alias option that would be saved to .openzeppelin artifacts folder

<img width="775" alt="Screenshot 2024-05-29 at 22 06 08" src="https://github.com/OpenZeppelin/openzeppelin-upgrades/assets/167001185/5fb80c65-6f06-4a47-b1d3-c057961813a0">

**Comment by ericglau** [comment]
Right, running `deployProxy` more than once would just deploy several proxies, and there isn't a way to re-use existing proxies.  However, this plugin is not intended to be a deployment address tracker and I think tracking aliases would be out of scope.  You could track your proxy deployments separately if needed.
