### ISSUE TITLE
Cannot find module @openzeppelin/defender-sdk-base-client/lib/index.js

### ISSUE THREAD

**Issue by ponyjackal** [OpenZeppelin/openzeppelin-upgrades#1028]
Hi. I'm trying to deploy a simple upgradeable contract. I'm following the documentation at [https://docs.openzeppelin.com/defender/v2/tutorial/deploy 2](https://docs.openzeppelin.com/defender/v2/tutorial/deploy) using hardhat

Since Hardhat now uses ignition, is not creating the scripts folder as the documentation says, So I have create the folder and the deploy.ts file manually

this is what I get:

`npx hardhat run --network sepolia scripts/deploy.ts

Error: Cannot find module '/Users//git//defender_test/node_modules/@openzeppelin/defender-sdk-base-client/lib/index.js'. Please verify that the package.json has a valid "main" entry`

any idea?

**Comment by 0xSunshine** [comment]
google is your friend https://github.com/OpenZeppelin/defender-sdk/issues/367

**Comment by 0xSunshine** [comment]
> Hi. I'm trying to deploy a simple upgradeable contract. I'm following the documentation at [https://docs.openzeppelin.com/defender/v2/tutorial/deploy 2](https://docs.openzeppelin.com/defender/v2/tutorial/deploy) using hardhat
> 
> Since Hardhat now uses ignition, is not creating the scripts folder as the documentation says, So I have create the folder and the deploy.ts file manually
> 
> this is what I get:
> 
> `npx hardhat run --network sepolia scripts/deploy.ts
> 
> Error: Cannot find module '/Users//git//defender_test/node_modules/@openzeppelin/defender-sdk-base-client/lib/index.js'. Please verify that the package.json has a valid "main" entry`
> 
> any idea?

google is your friend https://github.com/OpenZeppelin/defender-sdk/issues/367

although @spalladino @Amxx is it possible to get an ETA on this urgent toolchain issue fix?
