### ISSUE TITLE
6 high severity vulnerabilities in @openzeppelin/hardhat-upgrades: ^3.1.1 and downgrade the version to  2.1.1

### ISSUE THREAD

**Issue by Cainuriel** [OpenZeppelin/openzeppelin-upgrades#1039]
original pachage:

```
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.4"
  },
  "dependencies": {
    "@openzeppelin/contracts-upgradeable": "^5.0.2",
    "@openzeppelin/hardhat-upgrades": "^3.1.1",
    "dotenv": "^16.4.5",
    "ethers": "^6.13.0"
  }
  ```

when I try to start a repo with the latest version of the @openzeppelin/hardhat-upgrades I get 6 high security alerts.

When trying to fix it with the ``` npm audit ``` by forcing the solution is downgrade the library to version: ``` 2.1.1 ```:

```
Will install @openzeppelin/hardhat-upgrades@2.1.1, which is a break change
node_modules/@ethersproject/providers/node_modules/ws
  @ethersproject/providers <=5.7.2
  Depends on vulnerable versions of ws
  node_modules/@ethersproject/providers
    ethers 5.0.0-beta.119 - 5.7.2
    Depends on vulnerable versions of @ethersproject/providers
    node_modules/@openzeppelin/defender-admin-client/node_modules/ethers
    node_modules/eth-gas-reporter/node_modules/ethers
      @openzeppelin/defender-admin-client *
      Depends on vulnerable versions of ethers
      node_modules/@openzeppelin/defender-admin-client
        @openzeppelin/hardhat-upgrades >=2.2.0
        Depends on vulnerable versions of @openzeppelin/defender-admin-client
        node_modules/@openzeppelin/hardhat-upgrades
      eth-gas-reporter >=0.2.26
      Depends on vulnerable versions of ethers
      node_modules/eth-gas-reporter

6 high severity vulnerabilities

```
my package finally:

```
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.4"
  },
  "dependencies": {
    "@openzeppelin/contracts-upgradeable": "^5.0.2",
    "@openzeppelin/hardhat-upgrades": "^2.1.1",
    "dotenv": "^16.4.5",
    "ethers": "^6.13.0"
  }
```

Even so, serious vulnerabilites are available with:

```
fix available via `npm audit fix`
node_modules/@ethersproject/providers/node_modules/ws
  @ethersproject/providers  <=5.7.2
  Depends on vulnerable versions of ws
  node_modules/@ethersproject/providers
    ethers  5.0.0-beta.119 - 5.7.2
    Depends on vulnerable versions of @ethersproject/providers
    node_modules/eth-gas-reporter/node_modules/ethers
      eth-gas-reporter  >=0.2.26
      Depends on vulnerable versions of ethers
      node_modules/eth-gas-reporter

4 high severity vulnerabilities
```
With such a low version of openzeppelin/hardhat-upgrades will it not affect the manifest of the contracts since the project has already started deployments and all this came about in an update?

What would be the most stable and suitable configuration for an upgradeable contract project?

**Comment by ericglau** [comment]
- The latest version of `@openzeppelin/hardhat-upgrades` (e.g. currently 3.1.1) is recommended
- [ethers v6.13.1](https://github.com/ethers-io/ethers.js/releases/tag/v6.13.1) is available to address the possible `ws` vulnerability. You should update your dependencies to use that.
- The Hardhat Upgrades plugin's dependency on `@openzeppelin/defender-admin-client`, which depends on an older version of ethers, is only used with Defender legacy (which is deprecated) and [will be removed](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1040).
- npm reported vulnerabilities may not be relevant to hardhat-toolbox.  See https://github.com/NomicFoundation/hardhat/discussions/3945

**Comment by Cainuriel** [comment]
So, in principle, I have to upload the ethers version and this will preserve the version of @openzeppelin/hardhat-upgrades?

**Comment by ericglau** [comment]
`@openzeppelin/hardhat-upgrades` has peer dependencies (see its [package.json](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/package.json)) using semantic versioning on ethers and hardhat, so should be forward compatible with the current major versions of those.

**Comment by Cainuriel** [comment]
> * The latest version of `@openzeppelin/hardhat-upgrades` (e.g. currently 3.1.1) is recommended
> * [ethers v6.13.1](https://github.com/ethers-io/ethers.js/releases/tag/v6.13.1) is available to address the possible `ws` vulnerability. You should update your dependencies to use that.
> * The Hardhat Upgrades plugin's dependency on `@openzeppelin/defender-admin-client`, which depends on an older version of ethers, is only used with Defender legacy (which is deprecated) and [will be removed](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1040).
> * npm reported vulnerabilities may not be relevant to hardhat-toolbox.  See [Fixing vulnerabilities in HardHat Toolbox NomicFoundation/hardhat#3945](https://github.com/NomicFoundation/hardhat/discussions/3945)

```
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.4"
  },
  "dependencies": {
    "@openzeppelin/contracts-upgradeable": "^5.0.2",
    "@openzeppelin/hardhat-upgrades": "^3.1.1",
    "dotenv": "^16.4.5",
    "ethers": "^6.13.1"
  }
```

with this change the same issues:

```
39 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```
And again the version has been downgraded to "^2.1.1":

```
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
fix available via `npm audit fix`
node_modules/@ethersproject/providers/node_modules/ws
  @ethersproject/providers  <=5.7.2
  Depends on vulnerable versions of ws
  node_modules/@ethersproject/providers
    ethers  5.0.0-beta.119 - 5.7.2
    Depends on vulnerable versions of @ethersproject/providers
    node_modules/eth-gas-reporter/node_modules/ethers
      eth-gas-reporter  >=0.2.26
      Depends on vulnerable versions of ethers
      node_modules/eth-gas-reporter

4 high severity vulnerabilities
```

**Comment by ericglau** [comment]
To be clear, I don't suggest downgrading to "^2.1.1", you should be able to use "^3.1.1"

The only reference to a vulnerable version of `ws` is with the following dependencies:
```
├─┬ @openzeppelin/hardhat-upgrades@3.1.1
│ └─┬ @openzeppelin/defender-admin-client@1.54.6
│   └─┬ ethers@5.7.2
│     └─┬ @ethersproject/providers@5.7.2
│       └── ws@7.4.6
```
and as per my comment above, that code path is deprecated.  So I don't see any issues here.

**Comment by Cainuriel** [comment]
> To be clear, I don't suggest downgrading to "^2.1.1", you should be able to use "^3.1.1"
> 
> The only reference to a vulnerable version of `ws` is with the following dependencies:
> 
> ```
> ├─┬ @openzeppelin/hardhat-upgrades@3.1.1
> │ └─┬ @openzeppelin/defender-admin-client@1.54.6
> │   └─┬ ethers@5.7.2
> │     └─┬ @ethersproject/providers@5.7.2
> │       └── ws@7.4.6
> ```
> 
> and as per my comment above, that code path is deprecated. So I don't see any issues here.
OK, we will not downgrade the version waiting for a prompt update. thank you very much.
