### ISSUE TITLE
`DocstringParsingError: Documentation tag exceeds the number of return parameters.`

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-upgrades#1047]
In this commit https://github.com/pcaversaccio/escrow-contract/commit/f4aba711276840d3a3134d9457242fd6e30a687d I updated my play-around repo to the latest dependency versions and the Hardhat tests started to fail (see [here](https://github.com/pcaversaccio/escrow-contract/actions/runs/10005945231/job/27657634191#step:9:30)):

```console
An unexpected error occurred:

Error: Failed to compile modified contracts for namespaced storage:

DocstringParsingError: Documentation tag "@return redeployProtectionFlag The 8-byte enum for the selection of a cross-chain redeploy protection." exceeds the number of return parameters.
   --> xdeployer/src/contracts/CreateX.sol:575:5:
    |
575 |     /**
    |     ^ (Relevant source part starts here and spans across multiple lines).



Please report this at https://zpl.in/upgrades/report. If possible, include the source code for the contracts mentioned in the errors above.
 ELIFECYCLE  Test failed. See above for more details.
Error: Process completed with exit code 1.
```

After investigation, I realised that via the `@tenderly/hardhat-tenderly` dependency, I also use `@openzeppelin/upgrades-core` which got upgraded as well to the latest `1.34.2` version. So the compilation issue is via my [`xdeployer`](https://github.com/pcaversaccio/xdeployer) Hardhat plugin, which also ships the [`CreateX`](https://github.com/pcaversaccio/createx) contract if you want to test local deployments.

Now the line that throws is [here](https://github.com/pcaversaccio/xdeployer/blob/300ff9f15b106d5dfeb76d0c71b01dc61186b54c/src/contracts/CreateX.sol#L914-L924):

```solidity
    /**
     * @dev Returns the enum for the selection of a permissioned deploy protection as well as a
     * cross-chain redeploy protection.
     * @param salt The 32-byte random value used to create the contract address.
     * @return senderBytes The 8-byte enum for the selection of a permissioned deploy protection.
     * @return redeployProtectionFlag The 8-byte enum for the selection of a cross-chain redeploy
     * protection.
     */
    function _parseSalt(
        bytes32 salt
    ) internal view returns (SenderBytes senderBytes, RedeployProtectionFlag redeployProtectionFlag) {
```

This was not an issue since the latest release. I don't see any DocString issue here since for each return value you use one `@return` tag.

**Comment by ericglau** [comment]
Thanks for reporting. This is fixed in [@openzeppelin/upgrades-core@1.34.3](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fupgrades-core%401.34.3)
