### ISSUE TITLE
CLI: Disallow self-references for storage layout validations

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-upgrades#1064]
If the [CLI](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-core#usage) is used with `--contract MyContract --reference MyContract`, or a contract `MyContract` has annotation `@custom:oz-upgrades-from MyContract`, this is a self-reference and doing so effectively makes upgrade safety validations pointless.

We should consider this incorrect usage and throw an error in this case.

Note that referencing the same contract name in a different build info file as introduced in https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/1062 is allowed.

If users do not have a reference contract available in the current project or any previous build info directory, they should use the `--unsafeSkipStorageCheck` option to skip storage checks.

**Comment by frangio** [comment]
> If users do not have a reference contract available in the current project or any previous build info directory, they should use the `--unsafeSkipStorageCheck` option to skip storage checks.

Is this also required for the first version one deploys? Asking because that doesn't seem like something that should be labeled unsafe.

**Comment by ericglau** [comment]
This does not apply to the first version, it only applies to subsequent versions (and in the case of Foundry, it would only apply when preparing or performing an upgrade).  The first version should not have and should not require a reference.
