### ISSUE TITLE
Including type-extensions.d.ts in the npm package

### ISSUE THREAD

**Issue by alcuadrado** [OpenZeppelin/openzeppelin-upgrades#145]
Hi

We just received some feedback that `buidler-upgrades` can't be easily used with typescript. 

I think you just forgot to include the `type-extensions.d.ts` in the npm package. I checked, and there's one in `src/`, but that folder is not present in the package.

**Comment by abcoathup** [comment]
Hi @alcuadrado!  Thanks so much for reporting the issue and passing on the feedback! 
The project owner will review and triage this issue as soon as they can.

**Comment by frangio** [comment]
Thanks @alcuadrado. Totally forgot to include that file in the package. Will release together with #149 once that's merged.

**Comment by frangio** [comment]
The fix has been released in `@openzeppelin/buidler-upgrades@1.0.2`.
