### ISSUE TITLE
does not handle initialize function overloading

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#146]
![image](https://user-images.githubusercontent.com/15959632/91642915-042b8e00-e9e4-11ea-8fac-e5dc04bf556c.png)

![image](https://user-images.githubusercontent.com/15959632/91642919-0857ab80-e9e4-11ea-8053-7ee36ab5c522.png)

**Comment by thegostep** [comment]
`Interface.getFunction()` needs to use the full initialize function signature to pull the correct abi https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments

**Comment by thegostep** [comment]
need to modify this line to use signature or sighash

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-buidler/src/deploy-proxy.ts#L59

**Comment by abcoathup** [comment]
Hi @thegostep!  I’m sorry that you had this issue.  

We have been able to reproduce this issue by following these steps:
1. Create a simple contract with two functions with the same name but different number of parameters
2. In a Buidler test, attempt to call `deployProxy` specifying the function as the initializer and provide the appropriate parameters.
3. The test errors with `Error: multiple matching functions (argument="name", value="store", code=INVALID_ARGUMENT, version=abi/5.0.2)`

This appears to be only with the Buidler plugin and I couldn't reproduce with the Truffle plugin.

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.

**Comment by frangio** [comment]
Thanks a lot for reporting this @thegostep!

I opened https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/149 to fix it by using `Interface.getFunction` from Ethers. Once we release the fix it should be possible to use all of [function name, signature, or selector](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments) to specify the chosen initializer.

**Comment by frangio** [comment]
The fix has been released in `@openzeppelin/buidler-upgrades@1.0.2`.
