### ISSUE TITLE
Which packages to use for solc v0.4?

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#154]
This is more of a support Q but figured you may be able to help out.

https://forum.openzeppelin.com/t/how-to-use-solidity-v4-with-openzeppelin-upgrades/3727

**Comment by frangio** [comment]
As I replied on the forum, for Solidity 0.4 you can install `openzeppelin-eth@2.0.2-standalone` which doesn't have a peer dependency on `zos-lib`.
