### ISSUE TITLE
Why upgrades-core doesn't include Proxy contracts source code? 

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/openzeppelin-upgrades#161]
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/package.json#L7

Now, I can't do something like:
```
npm i @openzeppelin/upgrades-core --save

import "@openzeppelin/upgrades-core/contracts/proxy/AdminUpgradeabilityProxy.sol";
```

**Comment by abcoathup** [comment]
Hi @rstormsf ,

Proxy contracts have been moved to OpenZeppelin Contracts since v3.2
https://forum.openzeppelin.com/t/openzeppelin-contracts-3-2-release-candidate/3718

**Comment by rstormsf** [comment]
got it. thx!

**Comment by abcoathup** [comment]
Closing this issue as resolved.

**Comment by frangio** [comment]
Yes, this package will probably soon be changed to use the contracts directly from OpenZeppelin Contracts too.

@rstormsf I would love to know what kind of setup you have and in what way you plan to use the proxy contracts. Are you planning to use the Buidler or Truffle plugins too?
