### ISSUE TITLE
Use proxies from OpenZeppelin Contracts package 

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#164]
The proxy contracts will be a part of OpenZeppelin Contracts starting at version 3.2. We should use the contracts directly from there, instead of vendoring them into upgrades-core.

**Comment by scnale** [comment]
Would this mean that the proxy contracts are compiled with the compiler version configured in the project (e.g. in `hardhat.config.ts`)?

**Comment by frangio** [comment]
@scnale Yes, why are you asking?

**Comment by frangio** [comment]
@scnale Yes I think so, why do you ask?

**Comment by scnale** [comment]
It just so happens that we modified a part of the plugin to be able to compile the proxy with a compiler version of our choosing. In particular, we wanted to compile with v0.8.9, a compiler without any known security issues. Was just wondering how to open an issue about this but I think there's no need to if our use case is covered by this issue.

**Comment by frangio** [comment]
I see. Now that I understand your question I realize the answer is actually no. (The proxies would be compiled with the hardhat config of this project (@openzeppelin/upgrades-core) where we specify the compiler version.) If there were any known security issues that affect these contracts we would choose a different compiler version.

**Comment by ericglau** [comment]
This is already done in the way described by the last comment above.
