### ISSUE TITLE
Allow implementation contracts with potentially unsafe operations (delegatecall or selfdestruct)

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-upgrades#167]
Allow implementation contracts with potentially unsafe operations (delegatecall or selfdestruct) via a flag such as `unsafeAllowPotentiallyUnsafeOperations`

Users who are aware of the risks but still want to proceed should be able to set a flag to allow.

Some examples of community members who have run into this restriction either with the plugins or the CLI:
https://t.me/zeppelinos/14628
https://forum.openzeppelin.com/t/trouble-with-testing-when-a-contract-has-a-selfdestruct-operation/2113

**Comment by frangio** [comment]
I'm not fond of the proposed flag. I would prefer a more granular approach allowing users to ignore a specific delegatecall or selfdestruct statement. This could be implemented via comments in the source code, although I don't know if the AST produced by solc includes comments.

**Comment by frangio** [comment]
I accidentally opened a duplicate https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/280. Closing in favor of that one.
