### ISSUE TITLE
Provide an instance of ProxyAdmin in the admin module

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#173]
We allow people to transfer ownership of the `ProxyAdmin` but don't provide access to the admin address, except through the network manifest file.

We can provide an instance of a `ProxyAdmin` contract abstraction attached to the right address. Furthermore, we can configure this instance so that the default sender is the owner of the contract. This will be very useful for people.

This sounds like it should clearly go in the `admin` module, but I don't know what name we can give it.

**Comment by abcoathup** [comment]
There could be an `admin.owner` or `admin.proxyAdminOwner` to expose the admin address (as there is `admin.transferProxyAdminOwnership`)
Then a `ProxyAdmin` could be used at that address to perform the upgrade.

**Comment by frangio** [comment]
I think it will be better for users if we provide the `ProxyAdmin` instance directly. The address, and even the owner address, can be obtained from there.

**Comment by frangio** [comment]
Fixed in #274.
