### ISSUE TITLE
Add a suggested solution to 'Deployment at address ... is not registered'

### ISSUE THREAD

**Issue by mverzilli** [OpenZeppelin/openzeppelin-upgrades#174]
I tried to call `prepareUpgrade` with a proxy address that is not registered in `.openzeppelin` and got this error message:

`Error: Deployment at address 0xfDf2E8257d5E3667Cb744348362AeE1ECFF24125 is not registered`

It'd be nice if, after that message, the function could add a suggestion on how to fix it. Something like:

`If you want to prepare an upgrade for a proxy at that address, register it by ...`

Note: I don't know whether we already provide away for users to trigger that registration by themselves, so this might not be possible at the current version? Either way, I think it would make for a better UX :).

**Comment by frangio** [comment]
It's not currently possible to register an existing proxy. Created https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/175 to track that feature. The difficulty lies in that we need the source code to calculate the current storage layout of the proxy.

We could still make this error friendlier by explaining that it can currently only be used with proxie deployed by the plugins.
