### ISSUE TITLE
Add documentation to use OpenZeppelin Contracts Upgradeable fork

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-upgrades#178]
Add documentation on using OpenZeppelin Contracts Upgrade Safe fork to Upgrades Plugins documentation.  

Community feedback is that this would be helpful and avoid community from using OpenZeppelin Contracts when they need to use the Upgrade Safe fork: 
https://forum.openzeppelin.com/t/how-to-use-ownable-with-upgradeable-contract/3336/10?u=abcoathup

**Comment by frangio** [comment]
This is currently documented in [Writing Upgradeable Contracts](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#use-upgradeable-libraries).
