### ISSUE TITLE
Deploying Upgradable Contracts Failed half way due to rising gas prices

### ISSUE THREAD

**Issue by miketeix** [OpenZeppelin/openzeppelin-upgrades#186]
Hi there, our contract deployment failed on mainnet half way through the process due to rising gas prices. Any idea if I can resume where it left off when the prices lower again / are more stable?

**Comment by abcoathup** [comment]
Hi @miketeix,

I am sorry to hear that you are being impacted by network congestion.

When an upgradeable project is first deployed, three contracts are deployed.

1. The logic contract
2. The ProxyAdmin
3. The proxy contract pointing to the logic contract along with calling the initialization logic.

Which transactions have been successful?

You can manually modify [`mainnet.json`](https://docs.openzeppelin.com/cli/2.8/configuration#network.json) in the `.openzeppelin` directory to record what contracts have been deployed and then rerun the `deploy` command. 

I recommend putting your [Configuration Files in Version Control](https://docs.openzeppelin.com/cli/2.8/configuration#configuration-files-in-version-control) before doing any modifications to your `<network_name>.json` file.

Please be aware that the network is still congested (https://www.ethgasstation.info/) so you will need to adjust your gas prices.

**Comment by loki-sama** [comment]
Thanks a lot that was very helpful.

**Comment by miketeix** [comment]
Indeed, thanks for the reply!

**Comment by frangio** [comment]
@miketeix @loki-sama Can you please clarify if your question was about the OpenZeppelin CLI or about the OpenZeppelin Upgrades Plugins?

I think @abcoathup's reply was about the CLI.

As for the plugins, you can rerun an operation and it will resume where it left off.
