### ISSUE TITLE
Use user-friendly names for manifest files

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#19]
We're currently using `${chainId}.json`, which results in files named like `0x7a69.json`. OpenZeppelin CLI uses a user friendly network name like `mainnet.json`, and anything that doesn't have a known name gets called `dev-${networkId}.json`. I think user friendly names make sense so that people know what the file is, but I don't like the `dev-` naming because some unknown ids will not be development, so maybe it should be `id-`.

**Comment by Hronom** [comment]
Relates https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/212
