### ISSUE TITLE
Using Proxy contracts from the main contracts repo?

### ISSUE THREAD

**Issue by stefek99** [OpenZeppelin/openzeppelin-upgrades#198]
Here: https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/master/packages/core/contracts/proxy

And here: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/proxy

### Almost the same but slightly different 😎

![image](https://user-images.githubusercontent.com/249703/96143527-1497b980-0efb-11eb-8814-ea5d57b48809.png)

**Comment by frangio** [comment]
See #164.

**Comment by stefek99** [comment]
Duplicate, of course.

BTW... I've just learnt that the Proxy and ProxyAdmin are precompiled!

Very interesting: https://forum.openzeppelin.com/t/add-instructions-on-how-to-verify-to-step-by-step-guides-for-using-upgrades-plugins/4148/3

> As for the proxy and the ProxyAdmin, they are precompiled with Solidity 0.6.8 currently, so when you deploy an upgradeable contract, you are only compiling your implementation contract with whatever Solidity version you want to use, whilst the precompiled versions of the proxy and ProxyAdmin are deployed.
