### ISSUE TITLE
Fails to deploy proxy without calling initialize

### ISSUE THREAD

**Issue by tsudmi** [OpenZeppelin/openzeppelin-upgrades#203]
Hi,

According to docs it should be possible to deploy proxy without calling initialize.
```javascript
  const Validators = await ethers.getContractFactory('Validators');
  await upgrades.deployProxy(Validators, []);
```
The code above fails with an error:
```
Error: types/values length mismatch (count={"types":3,"values":0}, value={"types":[{"name":"_pool","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"_solos","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"_settings","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true}],"values":[]}, code=INVALID_ARGUMENT, version=abi/5.0.7)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at AbiCoder.encode (node_modules/@ethersproject/abi/src.ts/abi-coder.ts:96:20)
      at Interface._encodeParams (node_modules/@ethersproject/abi/src.ts/interface.ts:267:31)
      at Interface.encodeFunctionData (node_modules/@ethersproject/abi/src.ts/interface.ts:297:18)
      at getInitializerData (node_modules/@openzeppelin/buidler-upgrades/src/deploy-proxy.ts:63:36)
      at Proxy.deployProxy (node_modules/@openzeppelin/buidler-upgrades/src/deploy-proxy.ts:46:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at deployValidators (deployments/validators.js:5:17)
      at Context.<anonymous> (test/Validators.test.js:38:40)
```

**Comment by julianmrodri** [comment]
I believe it will always call `initialize` when deploying for the first time. In your case its expecting parameters for that call. 

Can you point to the section of the docs where its says you can deploy Proxies without calling `initialize`?

**Comment by tsudmi** [comment]
Hi @julianmrodri , thanks for the quick response.

I found it here: https://docs.openzeppelin.com/upgrades-plugins/1.x/api-buidler-upgrades#deploy-proxy
"**If args is set**, will call an initializer function initialize with the supplied args during proxy deployment."

Also, according to [allowNoInitialization](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-buidler/src/deploy-proxy.ts#L58) variable it should be possible to create proxy without initialization.

**Comment by julianmrodri** [comment]
Thanks! Yes, you are right. Looks there might an issue then.  The challenge I see is how it can differentiate to not call the initialize vs call it but with no params.

**Comment by frangio** [comment]
Thanks for reporting!

In this case the documentation is not representing the intended behavior. If there is a function called `initialize`, `deployProxy` will always attempt to call it. (The variable `allowNoInitialization` is only used if the default initializer name is not found.)

If you want to work around this for now, you can change your contract so the "initializer" is calld something other than `initialize`.

There is a separate discussion that we can have regarding whether we should allow people to opt out of calling the default `initialize` function. Let me know your thoughts on this.

**Comment by tsudmi** [comment]
Hi @frangio ,

For now, I've overridden the `deployProxy` function for the cases where I want to call `initialize` manually:
```javascript
ProxyFactory.deploy(impl, adminAddress, '0x');
```

I have two contracts that would like to know each other addresses. I would like to deploy proxies for both and call `initialize` with the resulting addresses. It seems like this use case is not supported currently.

**Comment by frangio** [comment]
@tsudmi Rather than overriding internal functionality of the library I would recommend using the workaround I described above. You can, for example, change your initializer function to a different name like `setup`. If you do this (and do not specify `initializer: "setup"` as an option), `deployProxy` will deploy without initializing, and you can call initialization separately.

**Comment by frangio** [comment]
@tsudmi I've added the ability to skip initialization by specifying `initializer: false`.

**Comment by tsudmi** [comment]
Thanks @frangio
