### ISSUE TITLE
hardhat-plugins has not been published

### ISSUE THREAD

**Issue by robsecord** [OpenZeppelin/openzeppelin-upgrades#219]
this command fails:
`npm install --save-dev @openzeppelin/hardhat-upgrades`

with this error:
`'@openzeppelin/hardhat-upgrades@latest' is not in the npm registry.`

**Comment by johannbarbie** [comment]
while not published, i'm using this as a workaround:

`npm install 'https://gitpkg.now.sh/OpenZeppelin/openzeppelin-upgrades/packages/plugin-hardhat?master'`

**Comment by frangio** [comment]
Yes, we're sorting out the documentation (#218). The package will be released later today.

**Comment by drbullock** [comment]
> while not published, i'm using this as a workaround:
> 
> `npm install 'https://gitpkg.now.sh/OpenZeppelin/openzeppelin-upgrades/packages/plugin-hardhat?master'`

@johannbarbie did that work for you?

I'm getting this:
`ENOENT: no such file or directory, chmod 'C:\Token\node_modules\@openzeppelin\hardhat-upgrades\dist\scripts\migrate-oz-cli-project.js'`

**Comment by frangio** [comment]
`@openzeppelin/hardhat-upgrades` has been released now.

**Comment by frangio** [comment]
Please note there was an issue with `@openzeppelin/upgrades-core@1.3.0` (a dependency of `hardhat-upgrades`). You will need to make sure `@openzeppelin/upgrades-core@1.3.1` is installed.
