### ISSUE TITLE
Module '"../node_modules/hardhat/internal/lib/hardhat-lib"' has no exported member 'upgrades'.

### ISSUE THREAD

**Issue by johannbarbie** [OpenZeppelin/openzeppelin-upgrades#220]
the documentation mentions this:

`import {ethers, upgrades} from 'hardhat';`

yet the hardhat rewrite of buidler does not export any `upgrades`.

**Comment by frangio** [comment]
Hi @johannbarbie. What package have you installed? We merged the migration PR yesterday but haven't released it yet!

It will be released in a few hours today.

**Comment by frangio** [comment]
@johannbarbie `@openzeppelin/hardhat-ethers` has been released.

I cannot reproduce this issue, `upgrades` is correctly added to the Harhdhat environment. Let me know if you have issues.

**Comment by johannbarbie** [comment]
> upgrades is correctly added to the Harhdhat environment

that was the issue, thanks
