### ISSUE TITLE
Hardhat | Cannot read property 'deployProxy' of undefined

### ISSUE THREAD

**Issue by drbullock** [OpenZeppelin/openzeppelin-upgrades#223]
I am using the latest `@openzeppelin/hardhat-upgrades` and running the sample script for Hardhat Upgrades, but I am getting this error:

`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'deployProxy' of undefined`

This is the `packaje.json`:

```
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "chai": "^4.2.0",
    "ethereum-waffle": "^3.2.0",
    "ethers": "^5.0.19",
    "hardhat": "^2.0.3"
  },
  "dependencies": {
    "@chainlink/contracts": "0.0.11",
    "@openzeppelin/contracts-ethereum-package": "^3.0.0",
    "@openzeppelin/hardhat-upgrades": "^1.3.0"
  }
}

```

**Comment by frangio** [comment]
Please share your `hardhat.config.js`.

Do you have `require("@openzeppelin/hardhat-upgrades")` in it?

**Comment by drbullock** [comment]
Yes, @frangio , that was a silly issue, can you please add that in the readme.

**Comment by frangio** [comment]
Yes, good idea. https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/c489338b9d1446fea93ee1dd3bd0cb0af212f8b2
