### ISSUE TITLE
Compatibility with truffle-flattener

### ISSUE THREAD

**Issue by sydneyitguy** [OpenZeppelin/openzeppelin-upgrades#234]
It seems there's no easy way to create a flatten source code for `AdminUpgradeabilityProxy` at the moment because solidity source code is not included on the package and it's difficult to find the corresponding source code and compile options.

I failed verifying the `AdminUpgradeabilityProxy` on etherscan hundreds of times trying out all different versions of source code and compile options, but nothing worked.

It would be really nice if it's compatible with `truffle-flattener` so I can get the proxy source code easily like
`truffle-flattener node_modules/@openzeppelin/upgrades-core/contracts/AdminUpgradeabilityProxy.sol`

**Comment by frangio** [comment]
Hi @sydneyitguy. I'm sorry you have been having trouble with this.

It shouldn't be necessary to use `truffle-flattener` for verification. We can upload the solc JSON input that was used to compile.

What version of `@openzeppelin/upgrades-core` are you using?

**Comment by abcoathup** [comment]
Hi @sydneyitguy,

I have previously used the Builder (now Hardhat) Etherscan plugin to do multi-file verification of the proxy and ProxyAdmin on public networks. https://forum.openzeppelin.com/t/verify-upgrades-plugins-proxy-on-etherscan/3920

The proxy and ProxyAdmin contracts can be found in `@openzeppelin/upgrades-core`.

I was having issues verifying as multi-file, so in the end verified as a flat file, as per the post in the forum: https://forum.openzeppelin.com/t/generate-flattened-version-of-adminupgradeabilityproxy-sol/4691/6?u=abcoathup

If you need the proxy or ProxyAdmin verified on a public network, I am happy to help.

**Comment by sydneyitguy** [comment]
@frangio I'm using "@openzeppelin/upgrades-core@1.3.1"
If seems there's no AdminUpgradeabilityProxy.json file on my build directory.

`truffle run verify AdminUpgradeabilityProxy --network goerli` returns
```
Verifying AdminUpgradeabilityProxy
Could not find AdminUpgradeabilityProxy artifact at ./contract/build/contracts/AdminUpgradeabilityProxy.json
Failed to verify 1 contract(s): AdminUpgradeabilityProxy
```

I have successfully verified the proxy contract using a flatten file (Thanks @abcoathup for your help!)
I could generate the flatten source code by grabbing the source code from
- @openzeppelin/upgrades-core@1.3.1 repository
  - Proxy.sol
  - UpgradeabilityProxy.sol
  - AdminUpgradeabilityProxy.sol
- @openzeppelin/contracts@3.1 repository
  - Address.sol

and the compiler option:
- v0.6.8+commit.0bbfe453
- Optimization Enabled: No with 200 runs

**Comment by frangio** [comment]
Okay, I'm closing this issue as resolved. Compatibility with truffle-flattener in general will not be possible because we are using Hardhat. I've created https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/242 to tackle the more general issue of proxy verification.
