### ISSUE TITLE
Add option for silencing warnings

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#238]

**Comment by frangio** [comment]
Duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/226.

Note that we are considering printing a single warning rather than disabling them entirely.

**Comment by frangio** [comment]
@thegostep In case you didn't see it we've added a function to silence warnings in the latest release.

[@openzeppelin/hardhat-upgrades@1.4.0](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%401.4.0)
