### ISSUE TITLE
Automate verification of proxy contracts on Etherscan

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#242]
We want to override `hardhat-etherscan`'s `verify` task to completely verify an upgradeable proxy deployment. This includes: the user's implementation contract, the proxy, the proxy admin, and the beacon.

**Comment by abcoathup** [comment]
I deployed to public testnets using the current Truffle Upgrades Plugin and checked the verification status of the proxy and ProxyAdmin contracts:

## Ropsten
proxy (Flat): https://ropsten.etherscan.io/address/0x9b0920D981ef82A76132B5C06F5425fBEc1101Cd#code
ProxyAdmin (Flat): https://ropsten.etherscan.io/address/0x240b4b6237bE88a02344FcB8aD322ceC29F65A69#code

## Rinkeby
proxy (unverified): https://rinkeby.etherscan.io/address/0xE34Dafa9C53649B9a1c12B289de46Bef7A81cc55#code
ProxyAdmin (unverified): 
https://rinkeby.etherscan.io/address/0xF4D286F94A8D815A0F0458f7890728B6817C7D65#code

## Kovan
proxy (multi-file): https://kovan.etherscan.io/address/0x46C4E371A2616a335A13956ee9dd82CC58Cf3365#code 
ProxyAdmin (multi-file):
https://kovan.etherscan.io/address/0x3fFfF0a40E2E3152ab35D78cC49218dD2C35c6cc#code

## Goerli
proxy (flat): https://goerli.etherscan.io/address/0xBEbce112F17f8c561c4B2D470455a547419dC424#code
ProxyAdmin (unverified):
https://goerli.etherscan.io/address/0x16521c80dA11BfAD09230f19D680C7D59d48Fa76#code
