### ISSUE TITLE
proxy deployment fails when running alongside gas reporter

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#247]
https://github.com/cgewecke/hardhat-gas-reporter

![image](https://user-images.githubusercontent.com/15959632/100739302-2bc13680-33d7-11eb-9124-d0ad3f810287.png)

**Comment by frangio** [comment]
This is a bug in hardhat-gas-reporter. I've opened a PR with the fix. https://github.com/cgewecke/hardhat-gas-reporter/pull/48

**Comment by cgewecke** [comment]
@thegostep The fixed is published now with hardhat-gas-reporter v1.0.2. 

Please just lmk over there if you run into further problems.
