### ISSUE TITLE
Ignore struct errors originating in OpenZeppelin Contracts Upgradeable

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#248]
Given that we ensure storage compatibility for OpenZeppelin Contracts Upgradeable (only within the same major version though!), we could ignore the struct errors that originate in it. In order to check that the major version is the same we would have to retrieve and store the package version in the network file, since we can't tell otherwise.

An example is ERC20Snapshot, as reported by a user [in the forum](https://forum.openzeppelin.com/t/error-deploying-erc20snapshotupgradeable/4864).

**Comment by abcoathup** [comment]
Could use an Allow List rather than a binary selection to prevent potential upgrade safety issues being missed.

_From: https://forum.openzeppelin.com/t/error-deploying-erc20snapshotupgradeable/4864/3_
> I would suggest having an AllowCustomTypeInContracts whitelist in the plugin instead of all or nothing. It would make easier to not screw up in the future in other contracts.
