### ISSUE TITLE
upgrades package prevents hardhat compiler errors from reaching the console

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#250]
![image](https://user-images.githubusercontent.com/15959632/101058102-1261eb00-358d-11eb-8421-c410f74c26b6.png)

**Comment by frangio** [comment]
Thanks for reporting!

I was able to reproduce this but only when the error is a "stack too deep" error. Otherwise compiler errors do get through, which is why we hadn't seen this before.

**Comment by frangio** [comment]
Fixed in latest.
