### ISSUE TITLE
error after migrating from buidler to hardhat

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#264]
![image](https://user-images.githubusercontent.com/15959632/102834062-f2219100-43c0-11eb-9ba8-eb98e17e89d9.png)

**Comment by frangio** [comment]
@thegostep Can you try deleting `cache/validations.json`? It was a mistake on our part not to detect this change automatically but I think this should fix it.

**Comment by thegostep** [comment]
Nuking the cache did the trick - thank you!
