### ISSUE TITLE
Importing Interfaces breaks deployProxy

### ISSUE THREAD

**Issue by ccolorado** [OpenZeppelin/openzeppelin-upgrades#279]
Updated the Box contract used on `https://docs.openzeppelin.com/upgrades-plugins/1.x/truffle-upgrades`
Importing a simple interface.
Makes the migrate command to throw the following contract
Error: The requested contract was not found. Make sure the source code is available for compilation

When an interface is imported,  `checkForImportIdConsistency` removes a contract from the `input`,  `output` validated. 

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-truffle/src/validate.ts#L84-L105

.

@openzeppelin/truffle-upgrades/dist/validate.js 

```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

import "contracts/Itest.sol";
 
contract Box {
    uint256 private value;
 
    // Emitted when the stored value changes
    event ValueChanged(uint256 newValue);
 
    // Stores a new value in the contract
    function store(uint256 newValue) public {
        value = newValue;
        emit ValueChanged(newValue);
    }
 
    // Reads the last stored value
    function retrieve() public view returns (uint256) {
        return value;
    }

    function testing() public pure returns(bool) {
      return false;

    }

    function test() public view returns (bool) {
      Itest temp = Itest(address(this));
      return temp.testing();
    }
}

```

Oddly enough putting an inline interface presents works fine.

**Comment by abcoathup** [comment]
Hi @ccolorado!  I’m sorry that you had this issue.  

Unfortunately, I wasn’t able to reproduce this issue. I tried using the following:
## Itest.sol
```solidity
// contracts/Itest.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;
 
interface Itest {
    function testing() external pure returns(bool);
}
```

## Box.sol
```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

import "./Itest.sol";
 
contract Box {
    uint256 private value;
 
    // Emitted when the stored value changes
    event ValueChanged(uint256 newValue);
 
    // Stores a new value in the contract
    function store(uint256 newValue) public {
        value = newValue;
        emit ValueChanged(newValue);
    }
 
    // Reads the last stored value
    function retrieve() public view returns (uint256) {
        return value;
    }

    function testing() public pure returns(bool) {
      return false;

    }

    function test() public view returns (bool) {
      Itest temp = Itest(address(this));
      return temp.testing();
    }
}
```
## Deploy
```
$ npx truffle migrate --network rinkeby

Compiling your contracts...
===========================
> Compiling ./contracts/Box.sol
> Compiling ./contracts/Itest.sol
> Compiling ./contracts/Migrations.sol
> Artifacts written to /home/abcoathup/projects/forum/ccolorado/build/contracts
> Compiled successfully using:
   - solc: 0.7.5+commit.eb77ed08.Emscripten.clang



Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 10000000 (0x989680)


1_initial_migration.js
======================

   Deploying 'Migrations'
...
2_deploy_box.js
===============

   Deploying 'Box'
...
   Deploying 'ProxyAdmin'
...
   Deploying 'AdminUpgradeabilityProxy'
...
```

Can you provide the Solidity for `Itest.sol` and the command you ran?

**Comment by ccolorado** [comment]
Hi @abcoathup , 
command is:
 ` truffle compile --all && truffle migrate --reset`
contracts/Itest.sol code is:

```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

interface Itest{
  function testing() external view returns(bool);
}
```
Truffle v5.1.60 (core: 5.1.60)
Solidity - 0.7.0 (solc-js)
Node v10.23.1
Web3.js v1.2.9

**Comment by abcoathup** [comment]
Hi @ccolorado,

Unfortunately, I wasn’t able to reproduce this issue.

I tried the following:
Deployed to ganache-cli multiple times, with no other cleanup in between using `$ npx truffle compile --all && npx truffle migrate --reset`

What operating system are you using?  Is it case insensitive?

**Comment by ccolorado** [comment]
I see, I'll try to reproduce on another system. I am using 64 bit Linux (key sensitive).
If I am able to reproduce it on a different system, would a screen recording gif be any help?

**Comment by frangio** [comment]
@ccolorado A screen recording shouldn't be necessary. I'll take a look at this and get back to you.

**Comment by frangio** [comment]
@ccolorado Can you try using a relative import? As in: `import "./Itest.sol";`.

Note you are currently using `import "contracts/Itest.sol";`, this is an unusual import format that can cause issues sometimes.

**Comment by frangio** [comment]
I'll assume this was fixed by the change I suggested. Let us know if you have more questions!

**Comment by ccolorado** [comment]
Thanks.
I just tryied to reproduce on a new ubuntu vm and couldn't reproduce the issue.
Seems to be some kind of local issue I haven't figured out yet.

**Comment by hoiJuwon** [comment]
@ccolorado 
Hi, I am struggling same issue above. Can you tell me your new ubuntu vm version or truffle version which solve the issue?

**Comment by frangio** [comment]
@hoiJuwon Probably anything that isn't Windows would solve it. Try using WSL.

**Comment by hoiJuwon** [comment]
@frangio 
Im using mac os.We solved by upgrading solc version to 0.6.12 (from 0.5.6) Thx for reply👍

**Comment by parkjihwanjay** [comment]
Is there anyone having a problem with deployProxy in mac os m1 silicon?

**Comment by frangio** [comment]
@parkjihwanjay Can you describe your problem?

**Comment by parkjihwanjay** [comment]
Hi I'm using @openzeppelin/truffle-upgrades ^1.7.0 and my Computer is macbook air(m1, 2020), macOs BigSur.

I'm using solc version of 0.5.6 and before using @openzeppelin/truffle-upgrades, it compiled and migrated well. However, when I tried to deploy my contract with deployProxy which is provided by @openzeppelin/truffle-upgrades packages, I encountered with the error like below

```
The requested contract was not found. Make sure the source code is available for compilation
    at getContractNameAndRunValidation
```

The error occured for the contracts that import other contract like below

```solidity
import "./SafeMath.sol";
```

Thank you for reading 👍

**Comment by abuisine** [comment]
Hi have the same problem on a recent Intel based macbook :
```
#> truffle version
Truffle v5.4.12 (core: 5.4.12)
Solidity - 0.8.11 (solc-js)
Node v17.4.0
Web3.js v1.5.3
```
```
Error: The requested contract was not found. Make sure the source code is available for compilation
    at getContractNameAndRunValidation ([...]node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:48:11)
```
I seem to have the correct contract compiled with a correctly named json in the build folder

**Comment by SolidityGo** [comment]
> I see, I'll try to reproduce on another system. I am using 64 bit Linux (key sensitive). If I am able to reproduce it on a different system, would a screen recording gif be any help?

I fixed this problem by using `rm -rf ./artifacts  ./cache  ./.openzeppelin`

**Comment by TBomberman** [comment]
Hello, can we reopen this? I get this error at the moment I import any sol file locally.
When I use truffle compile --all && truffle migrate --reset I get "Artifacts are from different compiler runs"
Any help is appreciated! tia.

Truffle v5.4.1
Solidity v0.8.9
Node v16.5.0
Web3 v1.0.0
truffle-upgrades v^1.12.0
Windows 10

**Comment by frangio** [comment]
@TBomberman Can you share a repository where we could reproduce the issue?

**Comment by TBomberman** [comment]
> @TBomberman Can you share a repository where we could reproduce the issue?

I finally was able to get it to work in the end.
What I did was I had to reinstall truffle-upgrades by downgrading Node to v14.
I also have Truffle v5.4.29 now.
Not sure what was the issue exactly.
