### ISSUE TITLE
Logs are not decoded on Etherscan

### ISSUE THREAD

**Issue by IgorSenychCW** [OpenZeppelin/openzeppelin-upgrades#281]
We deployed my smart contract with truffle-upgrades and looks like Etherscan can't decode any event logs after that. When deploying without proxy contract everything works as expected. Can this behavior be related with upgrade plugins and proxy contract?

Transafer ownership transaction, OwnershipTransferred log wasn't decoded - https://rinkeby.etherscan.io/tx/0xf696c7de7f0825ab9bd79d88f2f217683680b65b8ea1ca1f465999d088a725e6

Implementation contract - https://rinkeby.etherscan.io/address/0x07d01a33486919929b2aa9116cdb1db89da81476#code
Proxy contract - https://rinkeby.etherscan.io/address/0xd4779334baa5184c3e9714dba5c4ed09989807e3#code

**Comment by frangio** [comment]
Thanks for reaching out @IgorSenychCW. This may be a limitation of Etherscan's support for proxies. I'll see if I can get more information. You may want to reach out to Etherscan as well.

**Comment by frangio** [comment]
@IgorSenychCW Take a look at [this transaction](https://etherscan.io/tx/0x19b82cde32c7b1b43bbe52aafef67790a0861fa043b53d30baa4fdd28a086647#eventlog) of USDC, which is also a proxy contract. Its events are not decoded either.
