### ISSUE TITLE
Solidity factory contract

### ISSUE THREAD

**Issue by ppoliani** [OpenZeppelin/openzeppelin-upgrades#287]
I remember in the depreciated openzeppelin-sdk one could deploy upgradable contract from within a Solidity code. More specifically there was

`"@openzeppelin/upgrades/contracts/application/App.sol";`

That allowed us to deploy contract like this:

`app.create(packageName, contractName, admin, encodedInitializeCall)`

Is there any way we can achieve the same thing with this current version of the package?

**Comment by abcoathup** [comment]
Hi @ppoliani,

To deploy upgradeable contracts from Solidity you can use the proxy contracts that were added to OpenZeppelin Contracts.  See: https://docs.openzeppelin.com/contracts/3.x/api/proxy

You can use the OpenZeppelin Upgrades Plugins in your tests to check the upgrade safety of your upgradeable contracts.

For a factory to create upgradeable contracts, please see the design discussions in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2339.

**Comment by frangio** [comment]
We don't currently have an out of the box factory contract but it should be relatively simple to build one using proxies from OpenZeppelin Contracts.

**Comment by ppoliani** [comment]
Hi @frangio @abcoathup,

Could you guys point to some example of how such factory can be built. I followed the links you provided however I believe it would be beneficial to everyone if such use case is documented given the sensitive nature of upgradable contracts.

**Comment by frangio** [comment]
There are many examples on the forum in [this thread](https://forum.openzeppelin.com/t/deploying-upgradeable-proxies-and-proxy-admin-from-factory-contract/12132).
