### ISSUE TITLE
Add method for obtaining implementation/template address

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#290]

**Comment by frangio** [comment]
What you call template is what we call implementation contract, right?

What is the use case for this?

**Comment by thegostep** [comment]
correct - the goal is to be able to programmatically verify them on etherscan

**Comment by frangio** [comment]
As a workaround, in the network files we generate, found in `.openzeppelin`, you will find the addresses of the implementations/templates and this should be all you need to verify using Hardhat with hardhat-etherscan, as long as the source code is available.

For example:

```
{
  "manifestVersion": "3.1",
  "impls": {
    "947293b16c213eed536798b441f166054d96eca618dd58fd573e57a2d327322e": {
      "address": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      ...
```

---

We've thought before about simplifying verification of proxies on Etherscan by providing a `verify-proxy` Hardhat command or something like that. We could also make this verify the implementation contract as well.

**Comment by thegostep** [comment]
an additional use case that comes to mind is being able to initialize the implementation contract after deployment

**Comment by abcoathup** [comment]
I am closing this in favor of similar issue https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/313
