### ISSUE TITLE
Use prepareUpgrade on already deployed project

### ISSUE THREAD

**Issue by abarmat** [OpenZeppelin/openzeppelin-upgrades#297]
I have a project that is already deployed for which I don't have a manifest file, it was deployed with custom scripts.

Is it possible to use prepareUpgrade() as a way to test a new implementation against what is already deployed?

**Comment by abcoathup** [comment]
Hi @abarmat,

Thanks for your question. 

You could write high level tests that use `deployProxy` and then `upgradeProxy` and this will check upgrade safety of upgrading from one implementation to another.

See the API documentation for usage in tests: 
* Truffle: https://docs.openzeppelin.com/upgrades-plugins/1.x/truffle-upgrades#test-usage 
* Hardhat: https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades#test-usage

Also see the step by step tutorials for example high level tests:
* Truffle: https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-truffle/3579
* Hardhat: https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-hardhat/3580 

----

You could also deploy your original implementation to a public testnet using the Upgrades Plugins and then use `prepareUpgrade` to check upgrade safety.

I will close this issue for now, if you need more information, you can post in the support section of the forum: ttps://forum.openzeppelin.com/c/support/upgrades/35

**Comment by abarmat** [comment]
Thank you

**Comment by frangio** [comment]
I agree with the recommendation to use `deployProxy` to get the current state in your tests. The reason this is necessary is that running `deployProxy` will store the necessary metadata for `upgradeProxy` to later check upgrade safety.

---

@abarmat Are you also interested in using the plugin for deploying to production, or only for testing?

**Comment by abarmat** [comment]
The idea is to have a process where I could test a new implementation to be storage safe against the latest deployed layout. 

Initially I would be happy to just run a check when testing the new implementation, even if then I had to deploy it to mainnet with our own deployment scripts. It seems that by keeping the older contract code along with the new code and writing a high level upgrade test will do.
