### ISSUE TITLE
Update @truffle/contract dependencies

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#321]
Based on this [advisory](https://npmjs.com/advisories/1648) truffle updated its web3 and possibly ethers.js dependencies.

**Comment by noobshow** [comment]
@openzeppelin/truffle-upgrades => @truffle/contract > ethers > elliptic
@openzeppelin/truffle-upgrades > @truffle/contract > web3

**Comment by frangio** [comment]
Thank you for reporting this @noobshow. Unfortunately there's nothing we can do about this in our package. Here's the dependency trail:

```
@openzeppelin/truffle-upgrades@1.5.0
└─┬ @truffle/contract@4.3.13
  └─┬ @truffle/interface-adapter@0.4.21
    └─┬ ethers@4.0.48
      └── elliptic@6.5.3
```

Truffle depends on Ethers v4, which has a fixed dependency on elliptic@6.5.3, so there is no way to update it to elliptic@6.5.4.

I've opened an issue in the Ethers repository to see if this can be fixed over there. https://github.com/ethers-io/ethers.js/issues/1439

**Comment by noobshow** [comment]
I reported same to @truffle/contract already same day, the core truffle has
made those changes...

npm reports like 1500+ vulnerable dependencies and they mostly point to
this plugin on my server.

Would watch out for the updated release soonest...

Thanks.

**Comment by frangio** [comment]
This is not something Truffle can fix unless they upgrade to Ethers v5.

**Comment by noobshow** [comment]
Thanks for the info... Switching to hardhat, seems to now suite my current style.
