### ISSUE TITLE
Verification of Proxy and ProxyAdmin failing using Hardhat

### ISSUE THREAD

**Issue by amateur-dev** [OpenZeppelin/openzeppelin-upgrades#326]
When using Solidity 0.8 in the contract and importing 
`import "@openzeppelin/contracts/proxy/utils/Initializable.sol"`
The contracts do get compiled in Solidity v 0.8.

However, when attempting to verify the contracts using
`npx hardhat verify --network <networkName> <address>`

Getting the following error: 
```
Error in plugin @nomiclabs/hardhat-etherscan: The bytecode retrieved could not have been generated by any of the selected compilers.
The expected version is 0.6.12.
The selected compiler version is: 0.8.0

Possible causes are:
  - Wrong compiler version selected in hardhat config.
  - The given address is wrong.
  - The selected network (kovan) is wrong.
```
While digging through the fx `upgrades.deployProxy` it is importing:

```
import AdminUpgradeabilityProxy from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/AdminUpgradeabilityProxy.sol/AdminUpgradeabilityProxy.json';
import ProxyAdmin from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/ProxyAdmin.sol/ProxyAdmin.json';
```

It appears that the `Initializable` contract at `node_modules/@openzeppelin/upgrades-core/contracts/Initializable.sol` is suited for `pragma solidity >=0.4.24 <0.7.0;`
Further, the contracts over here `https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/master/packages/core/contracts/proxy` are also suited for `pragma solidity ^0.6.0`

I believe this is the reason why I am not able to verify the contracts.

Link to github repo: [Sample Github Repo](https://github.com/amateur-dev/ozupgradableplayground.git)

**Comment by amateur-dev** [comment]
Similar error message:

```
(node:29788) UnhandledPromiseRejectionWarning: NomicLabsHardhatPluginError: The bytecode retrieved could not have been generated by any of the selected compilers.
The expected version is 0.6.12.
The selected compiler version is: 0.8.0
```

**Comment by abcoathup** [comment]
Hi @amateur-dev,

The proxy and ProxyAdmin are precompiled.  They should be verified on most public networks.  

Can you advise what version of Upgrades Plugins you are using, which network you have deployed to along with the address of your proxy and ProxyAdmin?

**Comment by amateur-dev** [comment]
```
"name": "@openzeppelin/hardhat-upgrades",
"version": "1.6.0",
```

I guess that pre-compilation is creating the issue.  Since harhat is trying to verify using solidity `0.8.0` but the other contracts are compiled at `0.6.12`

**Comment by amateur-dev** [comment]
Deployed network: Kovan
Implementation Address: 0x2a151C797ECC7e5568781a9DC8142d60aA61EDe1
Admin Address: 0x7A37391Df19a42c6b8C53d97846e47500C296b70
Proxy Address: 0x7a37391df19a42c6b8c53d97846e47500c296b70

**Comment by frangio** [comment]
The contracts are verified now. Sorry about the inconvenience. Should be automated very soon.

**Comment by iconofsin** [comment]
Is there a temporary automation workaround for this?

**Comment by frangio** [comment]
Not at the time.

**Comment by utgarda** [comment]
Thanks for the sample repo! Is there any piece of documentation describing non-automated verification?

**Comment by frangio** [comment]
Sorry, no. In [this forum post](https://forum.openzeppelin.com/t/verifying-already-compiled-upgradable-proxy-contracts-on-other-chains/9248/2?u=frangio) I share the JSON input used to compile the proxies.

It can be used with Etherscan to verify.

**Comment by Btadford** [comment]
Sorry, i don't understand how you fixed this issue. What did you do?

**Comment by frangio** [comment]
Please refer to our guide [How to verify a contract on Etherscan/BscScan/PolygonScan](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225), particularly the section about proxies.
