### ISSUE TITLE
Not able to deploy upgradable smart contract with initializer argument

### ISSUE THREAD

**Issue by ankitiitb1069** [OpenZeppelin/openzeppelin-upgrades#327]
I have two upgradeable smart contracts, one is getting deployed successfully.
The second contract requires address of first contract in initialize function.
I am getting the following error:

`"AdminUpgradeabilityProxy" -- The contract code couldn't be stored, please check your gas limit..`

Here is deployment code:

  
   
     module.exports = async function (deployer) {

       const existing = await TestNFT.deployed();

       await deployProxy(TestOperator, [existing.address] , { deployer, initializer:'initialize' });

    };

**Comment by frangio** [comment]
Hi @ankitiitb1069. Were you able to solve this?

**Comment by ankitiitb1069** [comment]
Yes, I was calling _grantRole of AccessControlUpgradeable in initializer function, replacing it with _setupRole worked just fine
