### ISSUE TITLE
"ProxyAdmin" -- only replay-protected (EIP-155) transactions allowed over RPC.

### ISSUE THREAD

**Issue by iyusdi** [OpenZeppelin/openzeppelin-upgrades#328]
I upgraded to truffle 5.3.2 to avoid this error on normal contract deploys, but it now fails when trying to deploy ProxyAdmin to mainnet. 

Two other contacts deploy in the same migration step before this, so truffle seems to be working. 

First my Migrations contract is deployed. (success)
Then my main contract is deployed. (success)

But the ProxyAdmin deploy fails with this error in the same migration step:

"ProxyAdmin" -- only replay-protected (EIP-155) transactions allowed over RPC.

**Comment by frangio** [comment]
Thank you for reporting this issue @iyusdi. How are you connecting to mainnet? Who is your provider?

**Comment by frangio** [comment]
This may be happening because `@openzeppelin/truffle-upgrades` has a direct dependency on `@truffle/contract`, which has to be updated separately. Can you make sure the version of `@truffle/contract` is 4.3.11 or greater?

**Comment by iyusdi** [comment]
I'll check on the @truffle/contract dependency and let you know, thanks.

**Comment by abcoathup** [comment]
Hi @iyusdi,

Did updating the `@truffle/contract` version resolve the issue?

**Comment by frangio** [comment]
Assuming this was due to an old version of `@truffle/contract`. Please reopen if the issue wasn't solved.
