### ISSUE TITLE
UUPSUpgradeable compile error

### ISSUE THREAD

**Issue by wanglonghong** [OpenZeppelin/openzeppelin-upgrades#353]
DocstringParsingError: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.
  --> @openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol:10:1:
   |
10 | /**
   | ^ (Relevant source part starts here and spans across multiple lines).

Solidity Version: 0.8.2
@openzeppelin/contracts-upgradeable: 4.1.0
hardhat: 2.2.1

**Comment by frangio** [comment]
Hi @wanglonghong. This is strange. Can you share minimal steps to reproduce this issue? I was able to compile the contracts using Solidity 0.8.2 as follows:

```
npm init -y
npm install hardhat @openzeppelin/contracts-upgradeable
```

```js
// hardhat.config.js
/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.2",
};
```

```solidity
// contracts/import.sol

pragma solidity ^0.8.2;

import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
```

**Comment by wanglonghong** [comment]
Hi @frangio Thank you for your reply.

I have tried again, but same issue.

package.json
"devDependencies": {
    "@eth-optimism/plugins": "0.0.4",
    "@nomiclabs/hardhat-ethers": "^2.0.1",
    "@nomiclabs/hardhat-etherscan": "^2.1.1",
    "@openzeppelin/hardhat-upgrades": "^1.7.0",
    "dotenv": "8.2.0",
    "ethers": "^5.1.4",
    "hardhat": "^2.2.1",
    "prettier-standard": "16.4.1",
    "rimraf": "3.0.2"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.1.0",
    "@openzeppelin/contracts-ethereum-package": "^3.0.0",
    "@openzeppelin/contracts-upgradeable": "^4.1.0",
    "chai": "^4.3.0",
    "web3": "^1.3.4"
  }

hardhat.config.js

require('dotenv').config()
require('@nomiclabs/hardhat-ethers')
require("@nomiclabs/hardhat-etherscan");
require('@openzeppelin/hardhat-upgrades');

module.exports = {
  solidity: "0.8.2",
  networks: {
    testnet: {
      url: process.env.NODE_URL,
      accounts: [process.env.PRIVATE_KEY]
    }
  },
  solidity: {
    compilers: [
      {
        version: '0.8.2',
        settings: {
          optimizer: {
            enabled: true,
            runs: 200
          }
        }
      },
    ]
  }
}

![image](https://user-images.githubusercontent.com/30057497/117223450-47c27b80-ae40-11eb-94e3-f59cfba0ce79.png)

**Comment by wanglonghong** [comment]
Hi @frangio 

[(https://github.com/Plutus-Gaming-NFTs-Reimagined/Plutus-Contracts)]

This is my repository which has above issue. Could you check AlturaNFTSwap.sol Contract?
Thank you so much

**Comment by frangio** [comment]
I cloned your repository, ran `npm install`, and then `npx hardhat compile` which worked correctly.

Not sure what could be going wrong on your side.

**Comment by wanglonghong** [comment]
Same issue on my end.

**Comment by wanglonghong** [comment]
Hi @frangio 
It is working on Ubuntu VM. I am not sure why not working on Windows10.

**Comment by frangio** [comment]
In the meantime you could try compiling with a more recent Solidity version.

**Comment by wanglonghong** [comment]
Thank you for your info

**Comment by frangio** [comment]
I was able to reproduce this on Solidity 0.8.2 on Windows (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2664). But Solidity 0.8.3 seems to be good! Please try that and let me know if you keep running onto the same issue.

There must be something wrong with the Windows binary for that version.

**Comment by wanglonghong** [comment]
Hi @frangio 
I could compile that on Solidity 0.8.4. Thank you. Btw could you help me for one more thing? I want to verify proxy contract which deployed using deployProxy (kind: 'uups'). but failed several times. 
If you can guide me simply, it will be great.

Thank you so much

**Comment by frangio** [comment]
@wanglonghong Yes, can you share the address? You can also email me if you prefer it not be public.

**Comment by wanglonghong** [comment]
{
  "manifestVersion": "3.2",
  "impls": {
    "95d7a95efaaf52ce2ade22b3fc4d470317448846783926ad2ac73960748168ac": {
      "address": "0xF54140B3317fA04798e224565834aE4AF45081C4",
      "txHash": "0xa263df1708eba39575e37a4b7bb20ec5f3ba5c1b733fc25ac054e4d81a0ed94b",
      "layout": {
        "storage": [
          {
            "contract": "Initializable",
            "label": "_initialized",
            "type": "t_bool",
            "src": "@openzeppelin\\contracts-upgradeable\\proxy\\utils\\Initializable.sol:23"
          },
          {
            "contract": "Initializable",
            "label": "_initializing",
            "type": "t_bool",
            "src": "@openzeppelin\\contracts-upgradeable\\proxy\\utils\\Initializable.sol:28"
          },
          {
            "contract": "ERC1967UpgradeUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\proxy\\ERC1967\\ERC1967UpgradeUpgradeable.sol:229"
          },
          {
            "contract": "UUPSUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\proxy\\utils\\UUPSUpgradeable.sol:36"
          },
          {
            "contract": "ERC165Upgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\utils\\introspection\\ERC165Upgradeable.sol:35"
          },
          {
            "contract": "ERC1155ReceiverUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\token\\ERC1155\\utils\\ERC1155ReceiverUpgradeable.sol:27"
          },
          {
            "contract": "ERC1155HolderUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\token\\ERC1155\\utils\\ERC1155HolderUpgradeable.sol:27"
          },
          {
            "contract": "ContextUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)50_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\utils\\ContextUpgradeable.sol:31"
          },
          {
            "contract": "OwnableUpgradeable",
            "label": "_owner",
            "type": "t_address",
            "src": "@openzeppelin\\contracts-upgradeable\\access\\OwnableUpgradeable.sol:20"
          },
          {
            "contract": "OwnableUpgradeable",
            "label": "__gap",
            "type": "t_array(t_uint256)49_storage",
            "src": "@openzeppelin\\contracts-upgradeable\\access\\OwnableUpgradeable.sol:74"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "alturaToken",
            "type": "t_contract(IERC20)3047",
            "src": "contracts\\AlturaNFTSwap.sol:30"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "alturaNFT",
            "type": "t_contract(IAlturaNFT)4303",
            "src": "contracts\\AlturaNFTSwap.sol:31"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "items",
            "type": "t_mapping(t_uint256,t_struct(Item)4340_storage)",
            "src": "contracts\\AlturaNFTSwap.sol:46"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "currentItemId",
            "type": "t_uint256",
            "src": "contracts\\AlturaNFTSwap.sol:47"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "totalSold",
            "type": "t_uint256",
            "src": "contracts\\AlturaNFTSwap.sol:49"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "totalEarning",
            "type": "t_uint256",
            "src": "contracts\\AlturaNFTSwap.sol:50"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "totalSwapped",
            "type": "t_uint256",
            "src": "contracts\\AlturaNFTSwap.sol:51"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "swapFee",
            "type": "t_uint256",
            "src": "contracts\\AlturaNFTSwap.sol:54"
          },
          {
            "contract": "AlturaNFTSwap",
            "label": "feeAddress",
            "type": "t_address",
            "src": "contracts\\AlturaNFTSwap.sol:55"
          }
        ],
        "types": {
          "t_contract(IERC20)3047": {
            "label": "contract IERC20"
          },
          "t_contract(IAlturaNFT)4303": {
            "label": "contract IAlturaNFT"
          },
          "t_mapping(t_uint256,t_struct(Item)4340_storage)": {
            "label": "mapping(uint256 => struct AlturaNFTSwap.Item)"
          },
          "t_uint256": {
            "label": "uint256"
          },
          "t_struct(Item)4340_storage": {
            "label": "struct AlturaNFTSwap.Item",
            "members": [
              {
                "label": "item_id",
                "type": "t_uint256"
              },
              {
                "label": "token_id",
                "type": "t_uint256"
              },
              {
                "label": "creator",
                "type": "t_address"
              },
              {
                "label": "owner",
                "type": "t_address"
              },
              {
                "label": "balance",
                "type": "t_uint256"
              },
              {
                "label": "price",
                "type": "t_uint256"
              },
              {
                "label": "creatorFee",
                "type": "t_uint256"
              },
              {
                "label": "totalSold",
                "type": "t_uint256"
              },
              {
                "label": "bValid",
                "type": "t_bool"
              }
            ]
          },
          "t_address": {
            "label": "address"
          },
          "t_bool": {
            "label": "bool"
          },
          "t_array(t_uint256)49_storage": {
            "label": "uint256[49]"
          },
          "t_array(t_uint256)50_storage": {
            "label": "uint256[50]"
          }
        }
      }
    }
  },
  "proxies": [
    {
      "address": "0xB63D84823e4FDD14ba41876Ce3E68Db531484cb6",
      "kind": "uups",
      "txHash": "0x8a5c2d9e60f1a90ec729079ea53452c97b9f6101801fa794c3f1b4c993e04e83"
    }
  ]
}


I have deployed it on BSC testnet.

**Comment by wanglonghong** [comment]
Hi @frangio 
Do you need anything else?

**Comment by frangio** [comment]
I've reported the Windows issue to the Solidity team: https://github.com/ethereum/solidity/issues/11358

As a workaround for anyone running into this, please use Solidity 0.8.3 on Windows.
