### ISSUE TITLE
UUPS: Warning: A proxy admin was previously deployed on this network.

### ISSUE THREAD

**Issue by rellfy** [OpenZeppelin/openzeppelin-upgrades#369]
After a clean install, deploying only UUPS proxy contracts, the following warning is thrown during each contract deployment for a local hardhat network.
```
Warning: A proxy admin was previously deployed on this network.
```
My guess is that the plugin still deploys a proxy admin for UUPS proxies, or that somehow some data from my previous Transparent proxy deployments is still in my computer somewhere, triggering the alert -- but as I said, I did try with a clean dependency install.

**Comment by frangio** [comment]
Thank you for reporting @rellfy.

Did you delete the `.openzeppelin/unknown-31337.json` file? This is the network file for Hardhat Network.

**Comment by rellfy** [comment]
> Thank you for reporting @rellfy.
> 
> Did you delete the `.openzeppelin/unknown-31337.json` file? This is the network file for Hardhat Network.

Thanks, that was indeed what was triggering the warning.

**Comment by aspiers** [comment]
This doesn't fix it for me :-(

**Comment by aspiers** [comment]
I see it multiple times when running `hardhat test` on a test suite which calls `deployProxy` multiple times.  It pollutes the test suite output.  Is this a result of somehow the test code calling it in the wrong way, or is the warning simply not compatible with this approach to testing upgrades?

**Comment by frangio** [comment]
You will see this warning when you combine both Transparent and UUPS proxies. We may need to change the warning to be smarter about when it shows.

In the meantime, you can upgrade the `@openzeppelin/upgrades-core` dependency to the latest version and use `upgrades.silenceWarnings()`.

**Comment by aspiers** [comment]
Thanks for the info!  Is that the only possible cause?  What do you mean by combining both, exactly?  As far as I know I'm only using UUPS, but it's possible I've made a mistake somehow - is there any pitfall I should look out for?

**Comment by rellfy** [comment]
> Thanks for the info! Is that the only possible cause? What do you mean by combining both, exactly? As far as I know I'm only using UUPS, but it's possible I've made a mistake somehow - is there any pitfall I should look out for?

If you've ever used Transparent proxies before, and the proxy network file is cached/holds that data, it will emit this warning AFAIK.

**Comment by aspiers** [comment]
Never used Transparent, and also deleting `.openzeppelin/*.json` doesn't help.

**Comment by frangio** [comment]
You may not be including `{ kind: 'uups' }` in a call to `deployProxy`. If you omit that, it deploys as Transparent. We want to default to `'uups'` if the contract inherits `UUPSUpgradeable`, but it's not done yet.

**Comment by aspiers** [comment]
We're deploying like this:

```js
    const _MyContract = await ethers.getContractFactory(
      'MyContract'
    );
    MyContract = await upgrades.deployProxy(
      _MyContract,
      [ContractRegistry.address],
      { kind: 'uups' }
    );
    await MyContract.deployed();
```

so I'm pretty sure we're deploying UUPS.

**Comment by frangio** [comment]
Is this the only `deployProxy` call in your tests? If so, you should not be seeing this warning if you delete `.openzeppelin/*.json` and then run your tests. If the code is in a repository I'll gladly take a look.

**Comment by aspiers** [comment]
No it's called multiple times to deploy different contracts within the same test suite. Only the warning vanishes if I delete the json file first, so presumably the first deploy is recreating the manifest which then causes the warning on any subsequent deploys.

**Comment by frangio** [comment]
The first deploy creates a new manifest, which by default does not include an admin, because none has been deployed at that point. The first deploy of a transparent proxy will deploy an admin and store it in the manifest. If all of your deploys are UUPS, this will not happen. So if you see the warning, I'm certain a transparent poxy is being deployed.

If you open the manifest file you will find that it contains a `proxies` array with the kind of every proxy that has been deployed.

**Comment by aspiers** [comment]
Thanks a lot, that solved it!  There were indeed a couple of accidental omissions of `{kind: 'uups'}` from the deployments.

But I still don't fully understand the explanation - why wouldn't deployment of a UUPS proxy also store an admin in the manifest?  And why should there be a conflict between transparent and UUPS proxies as a result of only transparent proxies storing an admin?

To be honest I find the warning message very confusing (as you can probably tell by the length of this discussion!)  The warning just says that a proxy admin was previously deployed; it doesn't explain that it was a *transparent* proxy admin, nor does it explain why there should be a conflict between transparent and UUPS proxies.  What if I wanted to deploy a mix of the two proxy types?  Shouldn't that be possible without getting warnings?

Thanks again!

**Comment by rellfy** [comment]
> why wouldn't deployment of a UUPS proxy also store an admin in the manifest?

UUPS doesn't have a proxy admin: https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups

**Comment by frangio** [comment]
Yes, we need to improve these warnings. UUPS deployment does not use an admin, because it doesn't need it in the same way that Transparent proxies need it.

**Comment by aspiers** [comment]
> "UUPS deployment does not use an admin" caused me some confusion at first - I think I understand what you mean now, but I'd like to double check if that's OK?

Let me start by explaining the origin of my confusion as I understand it.  My thinking was as follows:

Any upgradeable proxy, including a UUPS proxy, needs at least one account which can upgrade it (let's ignore the crazy corner case where upgrade is a permissionless action which anyone can do).  So thinking intuitively without focusing on any details of how UUPS works, that account is the notional "admin" of the proxy.  Therefore according to that somewhat non-technical perspective of (say) a developer building these upgradeable proxies, or of an admin who wants to be able to upgrade them, it's somewhat confusing to read a statement saying that a UUPS deployment does not use an admin.

However, I *think* your point was that it is not the UUPS code itself which determines the admin, but the code of the underlying implementation - right?  And this is one of the main distinguishing features of UUPS vs. transparent: that UUPS delegates not only normal method calls, but also the management of the upgrade process itself.

In that respect, for UUPS proxies it is not OZ which is managing the admin role, whereas for transparent proxies it is.  Did I get that right?

So in the context of this issue report, it would be great if the error message these nuances somehow more clear.

Thanks a lot!

**Comment by Amxx** [comment]
> In that respect, for UUPS proxies it is not OZ which is managing the admin role, whereas for transparent proxies it is.

Exactly
