### ISSUE TITLE
Not able to use a different `from` account for upgrades.upgradeProxy

### ISSUE THREAD

**Issue by fab-spring** [OpenZeppelin/openzeppelin-upgrades#370]
According to the documentation, one should be able to upgrade a Proxy contract to a new logic contract via:
```
  const newProxy = await upgrades.upgradeProxy(proxy.address, newMain, { deployer })
```

However, I've tried changing `deployer` to a different account, and the caller of the transaction is always the same.
I'm using hardhat, not truffle.

**Comment by Amxx** [comment]
Hello @fab-spring 

This is an issue I have also encountered. This is because the transaction is sent using hardhat's `hre.provider`.
Unfortunately, I don't have an easy fix for you right now. I'll put that at the top or our list

**Comment by paulrberg** [comment]
Being able to set a new deployer would indeed be great.

**Comment by frangio** [comment]
There is some confusion about the `deployer` argument. This is Truffle's notion of a deployer object, the thing that keeps track of deployments during migrations.

For setting a new `from` argument, the workaround currently is to set it in the network configuration. But this doesn't work if you need different acounts for different deployments.

**Comment by paulrberg** [comment]
> For setting a new from argument, the workaround currently is to set it in the network configuration.

Can you show an example for this?

**Comment by frangio** [comment]
Yes, for example in `hardhat.config.js`:

```js
module.exports = {
  networks: {
    rinkeby: {
      from: '0x....',
    },
  },
};
```

**Comment by gzliudan** [comment]
Yes, sometimes we need different acount for different contract feature, such as during test. But below way is not working now:
```js
const instance = await deployProxy(Box, [42], { from: newAccount });
```
> For setting a new `from` argument, the workaround currently is to set it in the network configuration. But this doesn't work if you need different acounts for different deployments.

**Comment by frangio** [comment]
I apparently forgot about this, but the plugin will use the signer that comes attached to the `ImplFactory` in the Hardhat plugin, and I believe it also uses the same default that was set for the contract class passed in the Truffle plugin.

**Comment by frangio** [comment]
Closing in favor of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85.
