### ISSUE TITLE
Trouble with using owanable upgradeable contract with Truffle upgrades plugin

### ISSUE THREAD

**Issue by KaiStryker** [OpenZeppelin/openzeppelin-upgrades#375]
Been having trouble using ownable upgradable contract with my upgrades. When I deploy with the truffle upgrades plugin, if I have onlyOwner modifier on my contract, the deployment fails with a “owner is not the caller” error even tho when I test without the modifier the owner is properly set to the deployed address. 

Is this a bug you’ve noticed in the upgrade plugin? because there’s nothing actually wrong with my implementation.

I currently have the latest version of the plugin installed and will be downgrading to see if this issue still persists.

**Comment by Amxx** [comment]
Hello @KaiStryker 

First of all, you should make sure that you call the Ownable initializer before doing calling any function that has the onlyOwner modifier. Can you check that you are chaining the initializers (or leave a link to you code) ?

**Comment by KaiStryker** [comment]
Hi @Amxx 

Thanks for getting back to me. 

I chained the initializers. I verified this by deploying the base contract and calling the owner function on it, which returned the address I deployed from.

Here's a sample of my code for the contract:



    contract CoinSwap is PullPaymentUpgradeable, OwnableUpgradeable{
    
    ISwapRouter public constant UNISWAP_ROUTER = ISwapRouter(0xE592427A0AEce92De3Edee1F18E0157C05861564);
    IQuoter public constant UNISWAP_QUOTER = IQuoter(0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6);
    address private constant WETH9 = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
    address private constant multiDaiKovan = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
    address payable public feeRecipient;
    uint256 public swapFee;
    
    event tokenSwapped (address tokenIn, address tokenOut, address recipient, uint256 amountRecieved);

    function initialize(uint256 _swapFee, address payable _feeRecipient) external initializer{
        setFee(_swapFee);
        setFeeRecipient(_feeRecipient);
        __PullPayment_init();
        __Ownable_init();
    }

    function setFee(uint256 _swapFee) public onlyOwner{
        require(swapFee != _swapFee);
        swapFee = _swapFee;
    }

    function setFeeRecipient(address payable _feeRecipient) public onlyOwner{
        require(feeRecipient != _feeRecipient);
        require(_feeRecipient != address(0));
        
        feeRecipient = _feeRecipient;
    }


Here is the error I receive when the onlyOwner modifier is applied:

<img width="662" alt="Screen Shot 2021-06-11 at 6 19 52 PM" src="https://user-images.githubusercontent.com/78333221/121754080-b2bb3e00-cae1-11eb-9779-51fd8622af07.png">


Thanks for your help!

**Comment by Amxx** [comment]
You are calling setFee before you initialize the ownable contract...

**Comment by KaiStryker** [comment]
Haha how silly of me. Thanks for providing the extra pair of eyes
