### ISSUE TITLE
@custom:oz-upgrades-unsafe-allow for external-library-linking not valid for contracts

### ISSUE THREAD

**Issue by andreihrs** [OpenZeppelin/openzeppelin-upgrades#386]
DocstringParsingError: Documentation tag @custom:oz-upgrades-unsafe-allow not valid for contracts.
  --> contracts/Vault.sol:17:1:
   |
17 | /// @custom:oz-upgrades-unsafe-allow external-library-linking
   | ^ (Relevant source part starts here and spans across multiple lines).

My implementation is:

/// @custom:oz-upgrades-unsafe-allow external-library-linking
contract Vault is .....

**Comment by frangio** [comment]
`@custom` tags are only available for Solidity >=0.8.3.
