### ISSUE TITLE
hardhat deployProxy: "SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by nichanank** [OpenZeppelin/openzeppelin-upgrades#393]
Package versions:
```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@openzeppelin/contracts-upgradeable": "^4.1.0",
    "@openzeppelin/hardhat-upgrades": "^1.8.2",
    "ethers": "^5.4.1",
    "hardhat": "^2.3.0",
```

Getting an error with this in the tests:
```
const MyContract = await ethers.getContractFactory("MyContract");
myContract = await upgrades.deployProxy(MyContract, [arg1]);
await myContract.deployed();
```
The `deployProxy` line is giving a "Unexpected end of JSON input" error. It was running fine until I reinstalled my package dependencies today.

<img width="593" alt="Screenshot 2021-07-20 at 5 04 00 PM" src="https://user-images.githubusercontent.com/15038946/126305405-d7d192ab-5242-468d-aa69-02faaa06404d.png">

**Comment by frangio** [comment]
It sounds like your manifest file is not valid JSON. Can you open `.openzeppelin/<network>.json` and see if you spot what's wrong with it? You can share it here too.

**Comment by nichanank** [comment]
> It sounds like your manifest file is not valid JSON. Can you open `.openzeppelin/<network>.json` and see if you spot what's wrong with it? You can share it here too.

oh interesting, I was on hardhat network whose manifest file I'm assuming is `.openzeppelin/unknown-31337.json`, but this was an empty file. when do these get generated?

**Comment by frangio** [comment]
They get generated when there's something to write, like a new deployment. It's strange that it would be empty, I don't think that could be caused by the plugin. You should delete the file.

**Comment by nichanank** [comment]
> They get generated when there's something to write, like a new deployment. It's strange that it would be empty, I don't think that could be caused by the plugin. You should delete the file.

deleting the file solved the issue, it regenerated properly after i reran the test scripts. not sure what happened there. thank you!

**Comment by DEREK-DEV-AFK** [comment]
run `npx hardhat clean` and then compile it again
