### ISSUE TITLE
Update Initializable.sol with latest from OpenZeppelin Contracts

### ISSUE THREAD

**Issue by gzliudan** [OpenZeppelin/openzeppelin-upgrades#394]
The file packages/core/contracts/Initializable.sol writes: `pragma solidity >=0.4.24 <0.7.0;`, then this file is not support solidity 0.8.x? But file packages/core/contracts/import.sol writes: `pragma solidity ^0.8.0;`.

**Comment by frangio** [comment]
Generally you should use the `Initializable.sol` file that comes with OpenZeppelin Contract. This one has become outdated and hasn't been updated to support Solidity 0.8.

**Comment by creazy231** [comment]
Use this one: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol

**Comment by gzliudan** [comment]
Thanks.
