### ISSUE TITLE
Proxy admin is not the one registered in the network manifest

### ISSUE THREAD

**Issue by utgarda** [OpenZeppelin/openzeppelin-upgrades#396]
Deployed and verified proxy by cloning `openzeppelin-upgrades` and running `verify.js` from `packages/core`
https://rinkeby.etherscan.io/address/0x154695947213748E4e24Fb83Fb3DeB7A8c587583#code

Running script like 
```javascript
async function main() {
    const MY_CONTRACT = await ethers.getContractFactory("MyContract");
    const PROXY_ADDRESS = "0x154695947213748E4e24Fb83Fb3DeB7A8c587583";
    const upgraded = await upgrades.upgradeProxy(
        PROXY_ADDRESS,
        MY_CONTRACT,
        ["A", "B", "C"],
    );
}

main();
```

Getting an error message:
```
node_modules/@openzeppelin/hardhat-upgrades/src/upgrade-proxy.ts:67
        throw new Error('Proxy admin is not the one registered in the network manifest');
              ^
Error: Proxy admin is not the one registered in the network manifest
    at getUpgrader (node_modules/@openzeppelin/hardhat-upgrades/src/upgrade-proxy.ts:67:15)
    at Proxy.upgradeProxy (node_modules/@openzeppelin/hardhat-upgrades/src/upgrade-proxy.ts:35:23)
    at main (scripts/proxy/proxy_nft.js:12:22)
```

My reason for doing so is that I don't know how to verify the contract code itself otherwise.

How can I upgrade implementation _and_ have the proxy contract verified?

**Comment by Amxx** [comment]
Hello @utgarda 

Can you please confirm the `.openzeppelin` folder is present at each step. Is it being deleted during verification?

**Comment by utgarda** [comment]
Indeed, I tried to copy JSON files to another project and even hacked them replacing addresses. Probably messed them up.

**Comment by samw2k00** [comment]
is there a way to get the .openzeppelin/<chain>.json back if i accidentally deleted them

**Comment by ericglau** [comment]
@samw2k00 You can recreate the file with some manual steps.  See https://forum.openzeppelin.com/t/delete-openzeppelin-uncarefully-and-can-not-uprade-contracts-how-to-fix-it/20170/2
