### ISSUE TITLE
Error: Unsuported TypeName node type: FunctionTypeName at serializeTypeName (node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:43:13)

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#405]
Compiling a big project and this error came up, can't trim down the error but i think it relates to me using function type in a library:

```solidity
	function updateVault(
		Vault.Data memory vaultData,
		address TAddr,
		function(
			address,
			uint256,
			uint256,
			uint256,
			uint256,
			uint256
		) external onVaultUpdate
	) internal {
}

```

This happens on 0.8.4 solidity and `"@openzeppelin/hardhat-upgrades": "^1.9.0"`

**Comment by noobshow** [comment]
@frangio @Amxx 
Does openzeppeling-upgrades not support [function types](https://docs.soliditylang.org/en/latest/types.html#function-types)?

**Comment by noobshow** [comment]
Here is a stack trace of the error, i can't trim the project downward for now, but trying to get the tiniest possible code to get the root cause of the issue

Not sure if this helps with anything?
```
Error: Unsuported TypeName node type: FunctionTypeName
    at serializeTypeName (node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:43:13)
    at node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:48:72
    at Array.map (<anonymous>)
    at Object.getFunctionSignature (node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:48:55)
    at node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:168:25
    at Array.map (<anonymous>)
    at validate (node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:168:12)
    at OverriddenTaskDefinition._action (node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:57:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by noobshow** [comment]
I noticed as soon as i removed hardhat-upgrades from hardhat.config.ts, the project was able to compile without hitch

**Comment by Amxx** [comment]
Thank for the trace. It really helps. This is a bug on our end.

**Comment by Amxx** [comment]
@noobshow Do you use any other function types in your code?

The situation now:

- Error is triggered when we try to compute the function selector: https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/utils/function.ts#L43

- We compute the function selector for all external or public functions: https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/validate/run.ts#L166-L168

I'm not sure how to hash a function hash when the params include a function selector. I'm not even sure that it is allowed to put such an argument in a public or external function.

**Comment by noobshow** [comment]
> @noobshow Do you use any other function types in your code?
> 
> The situation now:
> 
> * Error is triggered when we try to compute the function selector: https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/utils/function.ts#L43
> * We compute the function selector for all external or public functions: https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/validate/run.ts#L166-L168
> 
> So the function param in an internal function shouldn't have triggered this. Working on a fix so it is supported in public and external functions.

Hi,
Thanks for getting back as fast as this(thought it would take days as it is a matter of urgency)....

I used multiple functions like that(in like around 5 to 7 locations), the most common structure is like this:

```
library TestLib {
	function IsDecAllowed(
		uint256 amount,
		function(address)
			external
			view
			returns (Vault.Data memory) vaultsData,
		Account.Config calldata accountConfig,
	) external view returns (bool) {
    }
}
```

That's the two structures i use, the one in the issue subject and this structure too.

I would be glad if i can use openzeppelin with this project before deployment so i can continue the usage for future upgrades(security checks, etc)... I'm actually using uups if that's important

**Comment by Amxx** [comment]
So I see you have some external functions with functions arguments. This is something we clearly didn't expect. It is not an issue with internal functions, but it is with external functions as we do save signatures to future-proof the manifest a bit more.

Hopefully, the fix is very simple (see #407). I'll double-check that with @frangio and we should have a new version released soon!

**Comment by noobshow** [comment]
Thanks so much, you don't know how much i appreciate the bug-fix and the expected release... 

Can't give enough thumbs-up... Thanks, once again

**Comment by frangio** [comment]
Should be fixed on `@openzeppelin/upgrades-core@1.8.1`.

**Comment by noobshow** [comment]
Not sure its necessary, but was just curious if hardhat-upgrade package should have its dependency bumped too?

My version upgrade isn't reflecting in hardhat-upgrades

**Comment by frangio** [comment]
Yarn resolutions shouldn't be necessary because hardhat-upgrades declares a compatible dependency. But it can be hard to get the transitive dependency to update in your lockfile... Perhaps `yarn add @openzeppelin/hardhat-upgrades@latest` would do it.
