### ISSUE TITLE
Deploy an Upgradeable contract without openzeppelin/hardhat-upgrades? 

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#406]
Is there a way to deploy and update an Upgradeable Smart contract without @openzeppelin/hardhat-upgrades?

I'm having issues compiling successfully with it and i hope the next time i need to update my smart contract, the bug would have been fixed or the feature would have been implemented

https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/405 is not allowing me compile for some unknown reasons and i can't even debug the task properly

**Comment by Amxx** [comment]
Hello @noobshow,

It is possible to deploy upgradeable contracts without the package. Upgradeability happens at the blockchain level, and the package is just tooling to simplify the deployment.

However, deploying by hand will not produce the manifest that you will later need to verify the consistency (security) of upgrades.
