### ISSUE TITLE
How to get Hardhat deployProxy gas used

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#414]
Hi,
I made [this post](https://forum.openzeppelin.com/t/how-to-get-hardhat-deployproxy-gas-used/14551) on the forum since almost 24 hours asking how to get total gas used when deploying using upgrades-plugin...

Here i'm Using this code for contract deployment and getting certain information after deployment

```
  const contract = (await upgrades.deployProxy(contractFactory, [], {
    kind: 'uups',
  })) as ContractType;
  await contract.deployed();

console.log(`contract address: ${contract.address}`);
console.log(`deployer address: ${contract.deployTransaction.from}`);
console.log(`gas price: ${contract.deployTransaction.gasPrice}`);
console.log(`gas used: ${contract.deployTransaction.gasLimit}`);

```
But, i figured there's a difference, big difference in "gas used" reported above vs "gas used" reported by hardhat-gas-reporter

How can i get the total gas used in deploying or upgrading a contract with its proxy?

**Comment by frangio** [comment]
For anyone else running into this there is a solution [in the forum thread](https://forum.openzeppelin.com/t/how-to-get-hardhat-deployproxy-gas-used/14551/3?u=frangio).
