### ISSUE TITLE
Is this possible to recreate the manifest file?

### ISSUE THREAD

**Issue by b1acKr0se** [OpenZeppelin/openzeppelin-upgrades#425]
Hello, thank you all for this awesome package. 

For some reasons, the generated manifest file for my contract was deleted. Is is possible to recreate it, given that I have the storage layout, the address/tx hash of the proxy as well as the admin's?  The only thing I couldn't figure out was the hashed key under the `impls` object:

```
"impls": {
    "8ab0960116e10161ba6e221402c11eff3ee771460a1ce9e322d87d9e6ecb3b5f": {
     }
}
```

Thank you.

**Comment by Amxx** [comment]
Hello @b1acKr0se 

Maybe @frangio can help you with that, he known the manifest structure better than anyone.

**Comment by frangio** [comment]
The hash is a hash of the bytecode, so it works as an identifier of the contract. If you're certain that the contract you have on disk is the same one that you have deployed at a particular address, you can assume that the hash is the same one that corresponds to that contract you have on disk.

Here's what I would suggest you do: deploy your system to a local Hardhat Network, and then copy over the `.openzeppelin/unknown-31337.json` file to `.openzeppelin/mainnet.json` (or whatever network), replacing all addresses with the addresses corresponding to mainnet. Note: You also need the implementation address. If you don't know it you can retrieve it using the function `upgrades.erc1967.getImplementationAddress` that was included in a recent release of the plugin.

Let us know how it goes!

We hope this will be less of a problem once we ship https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/175.

**Comment by b1acKr0se** [comment]
@frangio Thank you for your response. I have another manifest file which I previously deployed the contract to another chain, and indeed when I redeployed the contract to the local network, the deployed bytecode produces the same hash in the manifest file. So I think I can replace all the addresses and achieve the desired result. However I have not had an opportunity to perform an upgrade to my production contract so when I do, I'll make sure to update this post. Thanks again for this package!

**Comment by b1acKr0se** [comment]
I've done an upgrade on my production contract with a manifest file that I duplicated from another chain's. I can confirm that you only need to change the admin address, the proxy address, and the implementation address (given you have the same code as the one you deployed, so the generated bytecode would hash to the same key inside the `impls` object) to be able to perform the upgrade:

```
{
  "admin": {
    "address": "Admin address",
     ....
  },
  "proxies": [
    {
      "address": "Proxy address",
       ....
    }
  ],
  "impls": {
    "Hash of the deployed bytecode": {
      "address": "Implementation address",
      ...
    },
  }
}

```

Rest of the fields can be left unchanged. 

Thanks again to OpenZeppelin team!
