### ISSUE TITLE
contracts-upgradeable/proxy/Initializable.sol not found

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [OpenZeppelin/openzeppelin-upgrades#426]
Hi I am trying to run the upgrade examples of the documentation and after installing the openzeppeling upgrade contract I am having this error:

ParserError: Source "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol" not found
 --> project:/contracts/MonitoringCenter.sol:5:1:

The file is on node_modules/@openzeppeling folder

I am using ubuntu 20.04 and
npx truffle version
Truffle v5.4.10 (core: 5.4.10)
Solidity - 0.8.4 (solc-js)
Node v16.9.1
Web3.js v1.5.2

package.json 
{
....
  "devDependencies": {
    "@openzeppelin/contracts": "^4.3.1",
    "@openzeppelin/contracts-upgradeable": "^4.3.2",
    "@openzeppelin/test-helpers": "^0.5.13",
    "@openzeppelin/truffle-upgrades": "^1.9.1",
    "chai": "^4.3.4",
    "truffle": "^5.4.10"
  }
}
thanks in advance

**Comment by israel-gonzalezmedina** [comment]
file Initializable.sol is at 
node_modules/@openzeppelin/contracts/proxy/utils/Initializable.sol
why my node is not installing on the documentation path?

**Comment by frangio** [comment]
Can you try running `npm install` again? You have the right package version installed. The file should be there.

**Comment by israel-gonzalezmedina** [comment]
> Can you try running `npm install` again? You have the right package version installed. The file should be there.

I deleted node_modules folder and ran npm install and I get the same error. The file is just not there.

**Comment by frangio** [comment]
Oh yes, sorry I misread your issue. The documentation was wrong. The path you shared here is the right one.

I've fixed the docs now. https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/71cbfe8d3eabaef9908c19e60dedfb291c06f2d4
