### ISSUE TITLE
Configurable polling interval and polling timeout

### ISSUE THREAD

**Issue by 0x3bfc** [OpenZeppelin/openzeppelin-upgrades#453]
I am experiencing an issue with the following error: 

```
InvalidDeployment [Error]: No contract at address <CONTRACT_ADDRESS> (Removed from manifest)
```
The returned contract address is null in the transaction receipt. This happened when I use a non-geth RPC relayers to invoke transactions.

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/d2d79a2b039cda5c75a9110bf033e837e6949d69/packages/core/src/deployment.ts#L59

**Comment by dectf** [comment]
also encounter this problem, anyone help?

**Comment by frangio** [comment]
From the description here I don't see how changing the poll interval or timeout would help.

Can you describe how to reproduce the issue? Use a non-geth RPC relayer, then what action triggers the error exactly? Is this Ethereum mainnet or some other network?

**Comment by blabno** [comment]
Had same issue. I had to set `gasPrice` in network config in `hardhat.config.js`:
```javascript
{
      chainId: 80001,
      url: 'https://rpc-mumbai.maticvigil.com',
      accounts: [`0x${process.env.PRIVATE_KEY}`],
      gasPrice: ethers.utils.parseUnits('30', 'gwei')
};
```

**Comment by ericglau** [comment]
The [latest version](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%401.14.0) of the Hardhat Upgrades plugin includes [configurable timeouts](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/506) by using the `timeout` and `pollingInterval` options.  For more details, see the documentation for [Common Options](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#common-options).

We've also included a fix recently that [fixes some address issues from RPC endpoints](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/487), which may resolve the `No contract at address` error above.

Please try again with the latest version of the plugin if you are still experiencing the above issues.
