### ISSUE TITLE
Usage of SafeERC20 makes contract not upgrade-safe

### ISSUE THREAD

**Issue by ppoliani** [OpenZeppelin/openzeppelin-upgrades#455]
SafeERC20 from the Openzepelin contracts is a very popular Lib. However, using it in an upgradable contracts makes them non upgrade-safe according to the plugin.

More specifically, the following error is thrown

```
Error: Contract `Contract` is not upgrade safe
@openzeppelin/contracts/utils/Address.sol:185: Use of delegatecall is not allowed
    https://zpl.in/upgrades/error-002
```

At the moment I'm ignoring that error by setting

```
unsafeAllow: ['delegatecall']
```

However, this is unclear whether it will cause issues or not.

Would it be possible to clarify this point. SafeERC20 is a very popular lib so I believe many users will experience this issue.

**Comment by Amxx** [comment]
Hello @ppoliani 

`SafeERC20`, found in the `@openzeppelin/contracts` repository, does depend on `Address`, which contains non-upgrade-safe functions. Due to current limitations, we are not able to clearly identity which function in library are called, and if they are upgrade-safe... Thus making the `SafeERC20` flagged as potentially upgrade-unsafe.

A good option for you would be to use `SafeERC20Upgradeable` from the `@openzeppelin/contracts-upgradeable` repository. This version depends on `AddressUpgradeable` which is upgrade-safe.

**Comment by ppoliani** [comment]
Hi @Amxx,

Thanks for sharing the solution, I got one question. I checked the code in the `SafeERC20Upgradable` and from the looks of it works with `IERC20Upgradeable` in mind. I assume it would be equally correct to use `IERC20` instead as well. Is that correct?

**Comment by AmitayBohadana** [comment]
> unsafeAllow: ['delegatecall']

where should I put the "unsafeAllow: ['delegatecall']"
in order to ignore this error ?

**Comment by frangio** [comment]
@AmitayBohadana It goes in the options for `deployProxy`. Please refer to [the docs](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#deploy-proxy).

**Comment by koonopek** [comment]
There is the same problem with - "@openzeppelin/contracts/proxy/utils/Initializable.sol". It is very important to issue exactly this package from npm: `@openzeppelin/contracts-upgradeable` not this one `@openzeppelin/contracts` this should fix this issues

**Comment by jmendiola222** [comment]
I'm still getting this error on latest version, why is it close? The two proposals (using SafeERC20Upgradeable or unsafeAllow; delegatecall) are more like workarounds rather than fixes

**Comment by frangio** [comment]
@jmendiola222 Issue https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/240 is what would fix this problem.

**Comment by hadv** [comment]
> I'm still getting this error on latest version, why is it close? The two proposals (using SafeERC20Upgradeable or unsafeAllow; delegatecall) are more like workarounds rather than fixes

same here

```
@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol:185: Use of delegatecall is not allowed
```
