### ISSUE TITLE
Improve network file naming

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#465]
Development networks (Harhdat, Ganache), are named `.openzeppelin/unknown-3117.json` (or similar). Other "unknown" networks for which we don't have a name get the similarly named files, with the corresponding chain id, even if they're production networks (see https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/229). This causes a situation where it's not clear which of these files should be gitignored or not.

We can do better for development networks because by inspecting the `web3_clientVersion` we know it's a dev network if it contains TestRPC, I think.

In that case we should place things in a dedicated directory, possibly even in an ephemeral directory (e.g. `/tmp`) and we can also go further and try to somehow identify different instances of the test network and use a different file for each, since sharing the same file is a situation that can cause issues (although there are measures in place so that it doesn't).

**Comment by fassko** [comment]
This is the same with Polygon Mumbai Testnet.

I was wondering is there a way how to provide the name?

**Comment by frangio** [comment]
@fassko Unfortunately we don't have a way to manually provide the name.
