### ISSUE TITLE
Initializer not initializing value.

### ISSUE THREAD

**Issue by parash-namespace** [OpenZeppelin/openzeppelin-upgrades#466]
- The `TOEIAdmin` in [this contract](https://rinkeby.etherscan.io/address/0xd0e51fe7ebd82b9385761e400de9e55f699eef63#readContract) needs to be initialized.
- Deployment code
```const { ethers, upgrades } = require("hardhat");

async function main() {
  const TOEIAdmin = '0x63c056Dd2e576150f5e2BA0DA10927B8a62EF0Db'
  const TOEIMarketplaceFactory = await ethers.getContractFactory('TOEIMarketplace');
  const TOEIMarketplace = await upgrades.deployProxy(TOEIMarketplaceFactory, [TOEIAdmin], {initializer: 'initialize'});
  await TOEIMarketplace.deployed();
}

main()
  .then(() => process.exit(0))
  .catch(err => {
    console.log(err);
  });
```
- Contract initializer
```
import "@openzeppelin/contracts/proxy/utils/Initializable.sol";
contract TOEIMarketplace is Initializable {
    address public TOEIAdmin;

    function initialize(address _admin) public initializer {
        TOEIAdmin = _admin;
    }
}
```

**Comment by ericglau** [comment]
Hi @parash-namespace,

The `initializer` option should include the function signature of the initializer, including its parameters.  In your example where the initializer's parameter has type `address`, you can do either:
```
const TOEIMarketplace = await upgrades.deployProxy(TOEIMarketplaceFactory, [TOEIAdmin], {initializer: 'initialize(address)'});
```
or even omit the `initializer` option since the `initialize` name being used is already the default
```
const TOEIMarketplace = await upgrades.deployProxy(TOEIMarketplaceFactory, [TOEIAdmin]);
```

Note that the deployed contract at the link you provided has the initializer as `initialize(address _admin, uint256 _commissionPercent)`, so in that case you can call it like the following:
```
const TOEIMarketplace = await upgrades.deployProxy(TOEIMarketplaceFactory, [TOEIAdmin, commissionPercent]);
```

**Comment by parash-namespace** [comment]
Thanks @ericglau ,

Here is [the link](https://rinkeby.etherscan.io/address/0x5b138049da70ae2d981b916fde5fc20566a4b206#readContract) to newly deployed contract with suggested changes. Actually I had simplified the example to one argument for easier understanding.

However, the problem still exists.

**Comment by ericglau** [comment]
@parash-namespace Can you please elaborate on what the problem is and what you expect should happen?  Where are you seeing that the value is not initialized?  Thanks.

**Comment by parash-namespace** [comment]
@ericglau I am trying to initialize `TOEIAdmin` and `grossPay` using the deployProxy method in script and initializer method in the contract itself. But the contract has 0x000 for TOEIAdmin and 0 for grossPay though I have passed the args properly. 

I expect the values for the args in initializer to not be 0. I am able to later call the initializer (it seems anybody can).

Expectation: The initializer method to be called upon when the contract is deployed as the constructor originally worked.

**Comment by Amxx** [comment]
@parash-namespace Are you looking at the proxy or at the implementation code?

When you deploy a proxy:
- the logic (implementation is deployed)
  - this contract should not be used by itself, it should be locked without being initialized (sometime we use a constructor for that)
- a proxy is deployed, and points to the implementation
  - this contract is initialized. It is where and the state/parameters are stored.

**Comment by parash-namespace** [comment]
@Amxx Thanks. I understood your point. Now the problem is:

- My implementation contract still has an initialize method that can be called by anyone through etherscan.

**Comment by Amxx** [comment]
In most cases that is not an issue, but if you want to be safe, you can initialize it yourself (for example with admin set to 0xdead). That way you'll lock the implementation for good.

**Comment by parash-namespace** [comment]
@Amxx Thank you very much.

I deployed and ran the full contract with UI. It seems it works the way I wrote the code. I happened to check it in the implementation contract. Connecting ABI for proxy works as expected.
