### ISSUE TITLE
Error in Hardhatn - Cannot read property 'deployProxy' of undefined

### ISSUE THREAD

**Issue by damianlluch** [OpenZeppelin/openzeppelin-upgrades#468]
I have this error in Hardhat, I don't know why.

TypeError: Cannot read property 'deployProxy' of undefined

My code:

```
import {ethers, upgrades} from "hardhat"
import '@openzeppelin/hardhat-upgrades';

import readline from "readline"

async function deployNFT(privateKey:string) {
  const wallet = new ethers.Wallet(privateKey, ethers.provider)
  // Deploying
  const WSN = await ethers.getContractFactory("WonklySocial", wallet);
  const instance = await upgrades.deployProxy(WSN, [wallet]);
  await instance.deployed();

  console.log("Wonkly deployed to:", instance.address)
  console.log("Owner:", instance.deployTransaction.from)

}
```

**Comment by Amxx** [comment]
have you enabled the upgrades plugin in your `hardhat.config.json` ?

You need this line:
```
require('@openzeppelin/hardhat-upgrades');
```

**Comment by damianlluch** [comment]
Hi @Amxx , this is my tsconfig.json

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist"
  },
  "include": ["./scripts", "./test"],
  "files": ["./hardhat.config.ts"]
}
```


my hardhat.config.ts

```

**Comment by Amxx** [comment]
the ```import '@openzeppelin/hardhat-upgrades';``` line should not be in your script, it should be in your `hardhat.config.json`.

please put that just after `import "@nomiclabs/hardhat-waffle";` and see if it solves this.

@frangio This is not documented properly [here](https://docs.openzeppelin.com/upgrades-plugins/1.x/#install). I think we should update the doc.

**Comment by frangio** [comment]
Thanks, fixed in https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/b8dfb644a7b83f7bbeafb20f7f4762940f495874.

**Comment by vinkent420** [comment]
> have you enabled the upgrades plugin in your `hardhat.config.json` ?
> 
> You need this line:
> 
> ```
> require('@openzeppelin/hardhat-upgrades');
> ```

Thank @Amxx , you helped me a lots
