### ISSUE TITLE
A way to reconstruct a lost network file

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#474]
People accidentally delete or forget to commit their network files which actually contain information that is necessary for future upgrades. We need to provide a solution for this.

I'm thinking something like a command that they can run to reconstruct the network file given a proxy address. It can read the admin address (if transparent) from it, and the implementation address and try to match its bytecode to one of the contracts available locally. This is related to #175.

**Comment by haipro287** [comment]
i have just deleted my unknown-xx.json and now i cannot upgrade my contract any more, Is there any way for me to force my contract upgrade?

**Comment by ericglau** [comment]
@haipro287 We will be adding a way to import a previously deployed proxy soon.  For now, please see the workaround at https://forum.openzeppelin.com/t/upgrades-plugins-lost-my-network-files/11376/8 to manually recreate the deleted json file.

**Comment by haipro287** [comment]
> @haipro287 We will be adding a way to import a previously deployed proxy soon. For now, please see the workaround at https://forum.openzeppelin.com/t/upgrades-plugins-lost-my-network-files/11376/8 to manually recreate the deleted json file.

thank you, i will try this way ^^

**Comment by ericglau** [comment]
The latest release of the plugins now have a `forceImport` function that can import a previously deployed proxy.
Refer to the documentation for the `forceImport` function for [Hardhat](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#force-import) or [Truffle](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-truffle-upgrades#force-import).

This function can be used to reconstruct a lost network file by importing each of the previously deployed proxies using their address and corresponding contract implementation.
