### ISSUE TITLE
AdminUpgradeabilityProxy artifact byte code doesn't match with proxy contracts

### ISSUE THREAD

**Issue by technorhino** [OpenZeppelin/openzeppelin-upgrades#485]
Hi,
I have issues in verifying the Proxy contract in Avalanche fuji testnet, I'm using snowtrace explorer.
I have used **builder** plugin to deploy upgradable contracts and I see that the deployed AdminUpgradeabilityProxy contract byte code matches with the **"@openzepplin/upgrades-core"** package artifacts folder precompiled JSON bytecode.

Now I'm using hardhat to verify the contracts, for which I need the original Solidity contracts, the solc version & the optimization details to recompile to produce the same bytecode as Artifacts, I have tried different versions to compile the proxy contracts from the "Contracts folder" and it doesn't provide the same bytecode.

Details:
Versions: 
"@openzeppelin/buidler-upgrades": "1.2.1",
"@openzeppelin/upgrades": "2.8.0",
"@nomiclabs/buidler": "1.4.8",
"@nomiclabs/buidler-etherscan": "2.1.0",

Proxy Contract : https://testnet.snowtrace.io/address/0x6f35706e3af91ce262f63d9060d53be17bb889b4#code
Logic Contract: 0x2EEFE768041Cad8339E4c0E0107386c696d51DeB
Admin Contract: 0x4A9A4f0aA310c39C3693ACdD02f8901E905daeA1.

It would be a great help if you can help provide those details for the verification or include the original contracts with the upgrades-core folder

**Comment by Amxx** [comment]
Hello @technorhino 

When using the upgrades plugin, I expect some contract to be prepackaged (`TransparentUpgradeabilityProxy` and `AdminUpgradeabilityProxy` in particular). This means that the compiler settings are frozen and to NOT match the settings from your project.

If I remember correctly, the settings should be 
- solidity 0.8.2
- optimization on with 200 runs

**Comment by Amxx** [comment]
Here is one verified on mainnet: https://etherscan.io/address/0x4d3697643A8dDACdded1Eaa229d04d15D5fe90E8#code

**Comment by technorhino** [comment]
> Hello @technorhino
> 
> When using the upgrades plugin, I expect some contract to be prepackaged (`TransparentUpgradeabilityProxy` and `AdminUpgradeabilityProxy` in particular). This means that the compiler settings are frozen and to NOT match the settings from your project.
> 
> For "later" version, the settings should be
> 
> * solidity 0.8.2
> * optimization on with 200 runs
> 
> I'm not sure about older (>1 year) deployment though :/

Hello @Amxx ,

Thank you very much for your prompt reply.
I understand that the contracts are prepackaged, since our project is complex and cant immediately upgrade to latest versions, Is there any other way to find out what was the compiler settings used to produce the prepackaged artifacts? I can use the code and same settings to recompile to verify in avalanche.

**Comment by Amxx** [comment]
Do you have track of the software you used to deploy the proxy (package name and version ?)

**Comment by simsonraj** [comment]
> "@openzeppelin/buidler-upgrades": "1.2.1",
> "@openzeppelin/upgrades": "2.8.0",
> "@nomiclabs/buidler": "1.4.8",

Yea, this is the same as the ones mentioned in the description

"@openzeppelin/buidler-upgrades": "1.2.1",
"@nomiclabs/buidler": "1.4.8",
"@openzeppelin/contracts-ethereum-package": "3.0.0",

**Comment by technorhino** [comment]
> Do you have track of the software you used to deploy the proxy (package name and version ?)

Yea, its the same ones as mentioned in the description,
"@openzeppelin/buidler-upgrades": "1.2.1",
"@openzeppelin/upgrades": "2.8.0",
 "@openzeppelin/contracts-ethereum-package": "3.0.0"
 
 Is there something else I'm missing?

**Comment by Amxx** [comment]
`@openzeppelin/buidler-upgrades` used solidity 0.6.8. There is no mention of optimizations in the `builder.config.js`

The corresponding source code (contracts and builder config) is [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/%40openzeppelin/buidler-upgrades%401.2.0/packages/core)

**Comment by technorhino** [comment]
> `@openzeppelin/buidler-upgrades` used solidity 0.6.8. There is no mention of optimizations in the `builder.config.js`
> 
> The corresponding source code (contracts and builder config) is [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/%40openzeppelin/buidler-upgrades%401.2.0/packages/core)

Thanks @Amxx very much, i was able to verify the proxy Contract with the code reference.

**Comment by frangio** [comment]
Glad you were able to resolve it.

For anyone else seeing this, make sure to check out [our guide on verification](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225) on the Etherscan family of explorers. The Solc JSON input for verification of proxies is included in the section on Upgradeable Contracts and Proxies.
