### ISSUE TITLE
How to compile and get this TransparentUpgradeableProxy.json

### ISSUE THREAD

**Issue by millken** [OpenZeppelin/openzeppelin-upgrades#494]
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/742cc3e24f4cdcc81a4632c36074a9022fe800b7/packages/plugin-hardhat/src/utils/factories.ts#L6

**Comment by ericglau** [comment]
Hardhat is used to compile the contracts, which generates those json files.  See https://hardhat.org/guides/compile-contracts.html

For example, from the `packages/core` directory, run `npx hardhat compile` and that file will be generated in `packages/core/artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.json`

**Comment by millken** [comment]
@ericglau I got it, thank you.

**Comment by frangio** [comment]
If you need this for verification please see the section about proxies in [How to verify a contract](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225).
