### ISSUE TITLE
Testing in ropsten but having trouble upgrading the contract where the contracts says I am not the owner.

### ISSUE THREAD

**Issue by lazycoder1** [OpenZeppelin/openzeppelin-upgrades#496]
This is the address I try to run it by - https://ropsten.etherscan.io/address/0x0b3074cd5891526420d493b13439f3d4b8be6144 

Script I run - 
```
const { ethers, upgrades } = require("hardhat");

async function main() {
  // Deploying
  const Box = await ethers.getContractFactory("Box");
  const instance = await upgrades.deployProxy(Box, [42]);
  await instance.deployed();

  // Upgrading
  const BoxV2 = await ethers.getContractFactory("BoxV2");
  const upgraded = await upgrades.upgradeProxy(instance.address, BoxV2);
}

main();
```

A total of  4 transactions are placed and the last upgrade transaction fails because I am not the owner. It seems like I am not the owner of the proxy contract because some one else had deployed the proxy few days before me. 
https://ropsten.etherscan.io/tx/0x5ccb8c6d8220a7e0164ee18c69bc116537b673bdca86b66a08be6ada1f32c08f
https://ropsten.etherscan.io/tx/0x1e89edcc3dbeb05df003fac86647eecfd0e16b6b9fb0530a3070932aadb9518b
https://ropsten.etherscan.io/tx/0x472b6b087d5750d2b4123c4c017da6e2583fd0b28baab344cc717fb06b4eb114
https://ropsten.etherscan.io/tx/0x6e146adc857e6ac1909d23cfff214587d6938aba9990b51c29eadf87624554be

Last one fails with `Fail with error 'Ownable: caller is not the owner'` even though I am the person who has deployed it.

**Comment by lazycoder1** [comment]
This worked without a problem in rinkeby network though.

**Comment by frangio** [comment]
What versions of `@openzeppelin/hardhat-upgrades` and `@openzeppelin/upgrades-core` are you using?

**Comment by lazycoder1** [comment]
These are my dependencies, I am still able to reproduce it in ropsten. 

```"devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.3",
    "@nomiclabs/hardhat-etherscan": "^2.1.8",
    "@openzeppelin/hardhat-upgrades": "^1.12.0",
    "ethers": "^5.5.2",
    "hardhat": "^2.8.0"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.4.1",
    "@openzeppelin/contracts-upgradeable": "^4.4.1",
    "dotenv": "^11.0.0"
  }```

Pretty much used the following code with minor changes to use solidity 0.8.10 - https://github.com/t4sk/hello-oz-upgradeable#readme It was by a youtuber.

**Comment by ericglau** [comment]
In your upgrade script, you would need to set the address of the proxy that was previously deployed.  For example, change the address at https://github.com/t4sk/hello-oz-upgradeable/blob/main/scripts/upgrade_box_v2.js#L4 to the proxy address 0x2011dab8698e77a92a98966841a5827e5de3393f that was deployed in your second transaction above

**Comment by lazycoder1** [comment]
Ohh oh , this is really helpful. It solved the problem for me. 

I am planning on deploying 1 upgradable contract per customer of our all in one single project. Will need to take care of this file and see how I can manage it when there are 15+ contracts that will need to be upgraded.

**Comment by ericglau** [comment]
If you will be deploying and upgrading all of those, continue using the file for each of your deployments so that the plugin can keep track of them.  Do not delete it (to be clear, the only reason I mentioned deleting the original one from the repo is because that has someone else's deployments).  See this note from [readme](https://github.com/OpenZeppelin/openzeppelin-upgrades#how-do-the-plugins-work):

> The plugins will keep track of all the implementation contracts you have deployed in an .openzeppelin folder in the project root, as well as the proxy admin. You will find one file per network there. It is advised that you commit to source control the files for all networks except the development ones (you may see them as .openzeppelin/unknown-*.json).

On another note, if your 15+ contracts will all be using the same implementation (and when you upgrade, you want to upgrade all of them), you could consider using [beacon proxies](https://docs.openzeppelin.com/contracts/4.x/api/proxy) so that they can all be upgraded in a single transaction.  Support for that will available soon in the plugins - see https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/342

**Comment by lazycoder1** [comment]
Thanks a lot Eric, this was very helpful. Will read more on the links you have sent.
