### ISSUE TITLE
Refer to contracts with node_modules in path (hardhat)

### ISSUE THREAD

**Issue by progsmile** [OpenZeppelin/openzeppelin-upgrades#508]
Hi and thanks for package!
I'm using `slither` to analyze solidity code and it does not resolves paths to `node_modules`, so I have to manually import contracts, like this:
```js
pragma solidity ^0.8.9;

import "../node_modules/hardhat/console.sol";
import "../node_modules/@openzeppelin/contracts-upgradeable/access/AccessControlEnumerableUpgradeable.sol";
import "../node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "../node_modules/@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
...
```
And when I run `npx hardhat compile`, such error appears:
```
 TypeError: Cannot read property 'content' of undefined 
 at getSource (./.my-project-path../node_modules/@openzeppelin/upgrades-core/src/src-decoder.ts:22:53
 at ./.my-project-path../node_modules/@openzeppelin/upgrades-core/src/src-decoder.ts:33:31
```
It appears even when I fix paths to usual, but leave `import "../node_modules/hardhat/console.sol";` as is.
How can I set correct configuration to things get work or should it be considered as bug? Using package version `"@openzeppelin/hardhat-upgrades": "^1.12.0"` on  node `v16.5.0`
Thanks!

**Comment by frangio** [comment]
Hi @progsmile. How are you running Slither?

**Comment by progsmile** [comment]
I've checked once again and everything works perfect without full path. Seems like cache issues or kind of that. I run with:
`docker run -it -v /.../my-project-path:/share trailofbits/eth-security-toolbox`
`slither .`
