### ISSUE TITLE
What if the _defaultRoyaltyInfo is not set and royaltyInfo(...) is called? EIP-2981

### ISSUE THREAD

**Issue by ccarnino** [OpenZeppelin/openzeppelin-upgrades#511]
I was reading the new [EIP-2981 implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/common/ERC2981.sol).

I noticed that the `_defaultRoyaltyInfo` is undefined at constructor time and it can be unset with `_deleteDefaultRoyalty()`. But it is used without checking if it's set or not in `royaltyInfo(...)` function. 

Would this interrupt the execution? Shouldn't it be managed properly to accurately return royalties info?

Claudio

**Comment by ccarnino** [comment]
I apologise for the bogus bug report. 
I tested myself the new feature and when the `_defaultRoyaltyInfo` is not set, I confirm the execution completes correctly with output `(address: 0x0, fee: 0)`.

So I will close this issue

**Comment by frangio** [comment]
No problem @ccarnino, thank you for reviewing the code!

There is no notion of "undefined" or "unset" for Solidity storage variables. They are always zero-initialized.

**Comment by ccarnino** [comment]
That’s probably the bit of knowledge I was missing coming from other languages. Solidity is still relatively new for me. 
Thanks for the great work!

Claudio
