### ISSUE TITLE
Owner 0x000 when deploying an upgradeable token contract with upgrades plugin

### ISSUE THREAD

**Issue by vladx777** [OpenZeppelin/openzeppelin-upgrades#514]
Having an issue with initialising a standard wizard-generated upgradeable erc1155 contract using hardhat on the local network. 

The  contract gives its owner as 0x000, not the deployer address. When I run the initialize() function on it, it says:  'VM Exception while processing transaction: reverted with reason string 'Initializable: contract is already initialized'

What might be going wrong? How should we initialise an upgradeable contract? The docs are a bit lacking on this point.
Using upgrades package and all the rest as per the docs...

**Comment by vladx777** [comment]
@frangio @martriay guys, any thoughts how to fix this? Perhaps an example somewhere?

**Comment by ericglau** [comment]
Hi @vladx777, ensure that you are using the proxy address, not the implementation address.  Also, calling `deployProxy` with the upgrades plugin would have initialized the proxy (unless you disabled initialization), so it should not be necessary to call initialize() manually after deployment.

**Comment by vladx777** [comment]
@ericglau thanks, do you have an example? "using the proxy address, not the implementation address" - where is this being passed? docs don't seem to mention it or i haven't found it, thanks!

**Comment by ericglau** [comment]
[deployProxy](https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades#proxies) returns a contract instance with the proxy address.  You can use that instance directly in your Hardhat scripts, and/or you can get its address with `.address`.  There are some examples here: https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades#proxies

**Comment by vladx777** [comment]
@ericglau yes, i've seen that page and actually used the script for my deploy, but a call to my contract's owner returns 0x000... is this how it's supposed to be? 

to clarify, my question is not about the contract's address, it's about the owner's address

**Comment by vladx777** [comment]
Thanks. Here are the answers:

Can you check that you are calling __Ownable_init(); in your initializer? 
Yes, as it's part of the initialize() that is generated by the wizard:

```
function initialize() initializer public {
        __ERC1155_init("");
        __Ownable_init();
        __Pausable_init();
        __ERC1155Burnable_init();
        __ERC1155Supply_init();
    }
```

From the Debug Contracts in the UI:

![image](https://user-images.githubusercontent.com/96188570/152865644-88872fc4-b756-4f3c-a1df-43b8e8133971.png)
is showing 0x000

instance.owner() in command line in the console  is showing correctly though.

So the question is why the Debug Contracts tab is not showing the owner correctly.

**Comment by ericglau** [comment]
> From the Debug Contracts in the UI:

Which UI is that, can you share a link? It seems the owner was set properly since it works from command line.

**Comment by frangio** [comment]
@vladx777 Everything sounds like you're using the implementation address, as opposed to the proxy address. On the implementation address, the owner will be zero, and the contract will appear already initialized.

The UI looks like scaffold-eth. Can you share more of the code that you're using? Particularly how you're getting the address that you're querying. Possibly a repository where we can take a look.

**Comment by vladx777** [comment]
Yes, it's just scaffold eth's UI where I've simply replaced their YourContract template with Openzeppelin's ERC1155 upgradeable stuff from the wizard. Been trying to figure out how to deploy it there and just run a simple setURI on it via the UI. I've even added the hardhat's default account address to metamask to make sure the caller = deployer, still throwing an error. Any thoughts why it's not working?

**Comment by vladx777** [comment]
By the way, the upgrades package in the default script deploys the contract, but its functions don't display in the UI. Whereas deploying with the  await deploy("YourContract"... displays the functions, but is not letting us call them as the owner is 0x0...

**Comment by vladx777** [comment]
This might be the root cause of the issue, but not sure how to solve it

**Comment by ericglau** [comment]
scaffold-eth uses [hardhat-deploy](https://github.com/wighawag/hardhat-deploy#deploying-and-upgrading-proxies) which is not fully compatible with the OpenZeppelin Hardhat Upgrades plugin.  By default, hardhat-deploy only deploys the implementation contract (which is the root cause as you described), but you can also configure it to deploy a proxy.  You can see [their doc on proxies](https://github.com/wighawag/hardhat-deploy#deploying-and-upgrading-proxies) and [an example on stackexchange](https://ethereum.stackexchange.com/a/110605).

**Comment by night-king** [comment]
I have reproduce this, and found it is a mistake about deploy script:
if you use upgardeable: please write it like this:
  const YourContract= await ethers.getContractFactory("YourContract");
  const instance = await **upgrades.deployProxy**(YourContract, ['your initializer arguments']);
  await instance.deployed();
otherwise:
   const YourContract= await ethers.getContractFactory("YourContract");
  const instance = await **YourContract.deploy**(YourContract, ['your initializer arguments']);
  await instance.deployed();

hop help you.
