### ISSUE TITLE
Function Type Support

### ISSUE THREAD

**Issue by leonwilly** [OpenZeppelin/openzeppelin-upgrades#526]
First thank you for this wonderful open source library. It seems upgrades doesn't support function types inside structs. Even when simply upgrading the same contract unchanged it throws an incompatibility error. I'll give an example below to allow reproducing the error.

`Test.sol`
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";


contract TestV1 is Initializable, OwnableUpgradeable, UUPSUpgradeable {
    struct TestStruct {
        function () internal view returns (uint256) callback;
    }


    TestStruct test;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize() initializer public {
        __Ownable_init();
        __UUPSUpgradeable_init();
        test.callback = _callback;
    }

    function _callback() internal view returns (uint256) {
        return 1;
    }

    function _authorizeUpgrade(address newImplementation)
    internal
    onlyOwner
    override
    {}

}

contract TestV2 is TestV1 {

    function helloWorld() external view returns (uint256) {
        return 2;
    }
}

```

`deploy-test.js`
```js
// We require the Hardhat Runtime Environment explicitly here. This is optional
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `npx hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
const { ethers, upgrades } = require("hardhat");

async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using `node` you may want to call compile
  // manually to make sure everything is compiled
  // await hre.run('compile');
  const TestV1 = await ethers.getContractFactory("TestV1");
  const testV1 = await upgrades.deployProxy(TestV1, [], { kind: "uups" });
  const TestV2 = await ethers.getContractFactory("TestV2");
  await upgrades.upgradeProxy(testV1.address, TestV2);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

# Procedure
> $ hardhat node
$ hardhat run --network localhost ./scripts/deploy-test.js

# Results
> Solidity compilation finished successfully
Error: New storage layout is incompatible
contracts/Test.sol:13: Upgraded `test` to an incompatible type
> - Bad upgrade to struct TestV1.TestStruct
> - In struct TestV1.TestStruct
>   - Upgraded `callback` to an incompatible type
>     - Unknown type function () view returns (uint256)

Unless I am mistaken I see no reason why the above would fail considering the storage layout is unchanged in `TestV2`. 
Thanks in advance for any help you provide.

**Comment by Amxx** [comment]
There is already #477 about UDVT.

I'm starting a meta issue listing all unsupported types.

**Comment by leonwilly** [comment]
> There is already #477 about UDVT.
> 
> I'm starting a meta issue listing all unsupported types.

I'm sorry I did search for `Function Types` in the issues before posting and nothing relevant came up.

**Comment by Amxx** [comment]
Don't be sorry, #477 missed the function types, so your issue is more than welcome!

**Comment by leonwilly** [comment]
# Workaround
*warning this extremely dangerous and provides no guarantees that your storage layout is compatible*

1. Add the following import to `Test.sol`
```solidity
import "@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol";
```

2. Make the following changes to `deploy-test.js`
```js
async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using `node` you may want to call compile
  // manually to make sure everything is compiled
  // await hre.run('compile');
  const TestV1 = await ethers.getContractFactory("TestV1");
  const testV1 = await upgrades.deployProxy(TestV1, [], { kind: "uups" });
  const TestV2 = await ethers.getContractFactory("TestV2");
  const testV2Upgradeable = await ethers.getContractAt(
    "TransparentUpgradeableProxy",
    testV1.address
  );
  const testV2 = await TestV2.deploy();
  await testV2Upgradeable.upgradeTo(testV2.address);
  const upgradedTestV1 = TestV2.attach(testV1.address);
  console.log(await upgradedTestV1.helloWorld());
}
```
# Note
The above implementation requires you to call any method that is needed manually after the transaction is mined. Alternatively you could use the `upgradeToAndCall` method of the `TransparentUpgradeableProxy` using encoded function fragments if you would like a method called on the same transaction.
 
# Procedure
> $ hardhat run ./scripts/deploy-test.js

# Output
>  BigNumber { value: "2" }
