### ISSUE TITLE
Order of AST `linearizedBaseContracts` is not preserved 

### ISSUE THREAD

**Issue by 0xalpharush** [OpenZeppelin/openzeppelin-upgrades#540]
Whenever this package is imported in a hardhat config, it seems to change the order of `linearizedBaseContracts`. This causes issues for tools that parse the AST such as slither. The inheritance information is output by the compiler in a specific order, C3 linearization, and probably shouldn't be messed with. 

Please see https://github.com/crytic/slither/issues/1095 for more info.

I'm not sure, but this may be the code causing this issue. https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/345109b8ad49f249b31f785324e5ad715abfa5fe/packages/core/src/storage/extract.ts#L111-L116

**Comment by frangio** [comment]
Wow, thanks for reporting @0xalpharush. We should fix this as soon as possible.
