### ISSUE TITLE
Change Implementation of an unused but deployed contract

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#544]
Hi,
Does changing(not upgrading) an implementation contract to an entirely different structure work without problems, when no state/storage has been used?

There was an upgradeable contract deployment(proxy + implementation) that was successful, but i figured out the implementation deployed was the wrong one so i thought since no `state` or `storage` has been used, it might be safe to change the implementation to the actually correct one, am i wrong about that?

I can change the implementation manually if the packages doesn't allow me proceed with it.

Thanks in advance

**Comment by Amxx** [comment]
If the proxy doesn't have any storage set, then that should be safe. Not however that the initialisation might have set some storage.

Considering the price of deploying a proxy is very low compared to that of deploying an implementation I would advice using a new one just to be safe
