### ISSUE TITLE
Migration Error: The requested contract was not found.

### ISSUE THREAD

**Issue by boyuanx** [OpenZeppelin/openzeppelin-upgrades#549]
I've never had a problem with Truffle upgrades until my current project. Migration gives the following error:
`Error: The requested contract was not found. Make sure the source code is available for compilation`

Things I've tried:
- Deleting build folder
- Deleting the local repo and cloning again
- Re-adding truffle-upgrades plugin
- Making sure the plugins are of the latest version

I've tried looking up this issue online and none of the posts helped. Need urgent help on this as this is blocking our entire project. Thanks!

**Comment by boyuanx** [comment]
Yes - do I share it with you?

**Comment by ericglau** [comment]
@boyuanx You can share it with me and I'll take a look.

**Comment by ericglau** [comment]
I was able to reproduce the issue. Looking into it.

**Comment by ericglau** [comment]
@boyuanx I've identified the problem in the upgrades plugin where contracts are ignored if multiple parent contracts have the same name.  

In this case, this happens because a contract imports `@openzeppelin/contracts-upgradeable/interfaces/IERC20Upgradeable.sol` which imports `@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol`.  We should fix the plugin to detect this situation.

As a workaround for now, you can change the following line in your contract:
```
import "@openzeppelin/contracts-upgradeable/interfaces/IERC20Upgradeable.sol";
```
to
```
import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
```

**Comment by ericglau** [comment]
Minimal example to reproduce this issue:

Contract:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import "@openzeppelin/contracts-upgradeable/interfaces/IERC20Upgradeable.sol";
contract ImportIERC20  {
}
```
Migration:
```
const { deployProxy } = require("@openzeppelin/truffle-upgrades");
const ImportIERC20 = artifacts.require("ImportIERC20");
module.exports = async function (deployer) {
  await deployProxy(ImportIERC20, { deployer });
};
```

**Comment by ericglau** [comment]
@boyuanx As this issue can be reproduced with my comment above, please go ahead and remove me from your repo.  Thank you for bringing this to our attention.

**Comment by boyuanx** [comment]
Appreciate the quick response!

**Comment by adeebabdulsalam** [comment]
I had this same issue with hardhat plugin.

steps to reproduce

in contracts directory
-> contractA.sol (name: A)
-> contractB.sol 
```
interface A { ////}
contract B {  uses interface A }
```

solution:
changed the name of interface to IA in contractB.sol
