### ISSUE TITLE
Return ethers TransactionResponse for defender.proposeUpgrade

### ISSUE THREAD

**Issue by DsAtHuH** [OpenZeppelin/openzeppelin-upgrades#554]
After running `defender.proposeUpgrade` method from the [defender branch of HUH Governance](https://github.com/HUH-Token/huh-governance/tree/851670531c2d0e0c0d8dfd1aa48883fa0d5dc159) by running `yarn deploy rinkeby` the following error was triggered on the [verification task](https://github.com/HUH-Token/huh-governance/blob/851670531c2d0e0c0d8dfd1aa48883fa0d5dc159/src/upgrade.js#L36) just after the upgrade proposal was created:

```bash
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-rinkeby.etherscan.io/api
Reason: The Etherscan API responded that the address 0x76E12006dCDBdb62b591B0E87315ceC2a5Aae799 does not have bytecode.
This can happen if the contract was recently deployed and this fact hasn't propagated to the backend yet.
Try waiting for a minute before verifying your contract. If you are invoking this from a script,
try to wait for five confirmations of your contract deployment transaction before running the verification subtask.
```

When looking for the proposal object returned [here](https://github.com/HUH-Token/huh-governance/blob/851670531c2d0e0c0d8dfd1aa48883fa0d5dc159/src/upgrade.js#L24), I was expecting something similar to a `TransactionResponse` mentioned in [this answer in StackOverflow](https://stackoverflow.com/a/69013840). With a `TransactionResponse` coming from the deployment of the new implementation that takes place inside the `proposeUpgrade` method I would be able to write:

```javascript
const receipt = await tx.wait(5)
```

in order to programatically solve the requirement of Etherscan API.

**Comment by frangio** [comment]
This sounds reasonable. We currently return Defender's response object though, but we could add one more property to this object with the tx response.

**Comment by DsAtHuH** [comment]
> This sounds reasonable. We currently return Defender's response object though, but we could add one more property to this object with the tx response.

Is there already an estimation of when this feature will be available? In the meanwhile I can insert one minute delay as a workaround...

**Comment by ericglau** [comment]
Hi @DsAtHuH, we are looking into this but don't have an estimate at the moment.

**Comment by ericglau** [comment]
This is available in the latest release.
