### ISSUE TITLE
Storage upgrade reports false positives when old contract uses rename annotations

### ISSUE THREAD

**Issue by vvp** [OpenZeppelin/openzeppelin-upgrades#557]
It seems that in `@openzeppelin/upgrades-core` version 1.14.1, the `UpgradeableContract.getStorageUpgradeReport()` reports false errors when analyzing a storage upgrade from a contract that annotates the storage variables with `@custom:oz-renamed-from`.

I [created a gist](https://gist.github.com/vvp/ff9dff52864bb761df31e7a7bcea940e) containing example contracts along with a Hardhat+Mocha test case and the `ops` array output. I have not tested if the `@custom:oz-retyped-from` tags behave the same.

**Comment by frangio** [comment]
Thanks @vvp for providing easy reproduction steps. The reason this is happening is we ignore the actual variable name if the rename annotation is present, but only for the new contract layout and not for the old one.

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/d1f4c7acb3e1e72d18b0c23aaccfd58fac7efdda/packages/core/src/storage/compare.ts#L101

I proposed a fix in #558.
