### ISSUE TITLE
Deploy implementations and ProxyAdmin concurrently

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#56]
We currently serialize the deployment transactions for an implementation and a ProxyAdmin contract. For a faster experience we may want to send them to the blockchain at the same time. On the other hand, deploying a ProxyAdmin is only meant to happen once, and adding concurrency may increase the chance of odd issues happening, so we can decide to keep them serialized.

See https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/0004212f2b25c0ee3e11fd0eead26d70e03527a3 for an implementation of this idea for Buidler.

**Comment by ericglau** [comment]
Not needed anymore since proxy admins are deployed by the transparent proxy.
