### ISSUE TITLE
Docs: test example of upgradeProxy might fail when testing on actual situation.

### ISSUE THREAD

**Issue by robinxb** [OpenZeppelin/openzeppelin-upgrades#561]
In the [test-usage](https://docs.openzeppelin.com/upgrades-plugins/1.x/#test-usage) 
After call `await upgrades.upgradeProxy`, the transaction might not be finished yet, leading assert failure.

I've tested this on Rinkeby with proxy mode UUPS.

According to #354 , the example should be something like this,
```
  const intance = await upgrades.upgradeProxy(instance.address, BoxV2);
  await intance.deployed(); // or .deployTransaction.wait() ?
  assert.strictEqual(await instance.retrieve(), 42);
```

**Comment by frangio** [comment]
The test usage section doesn't include the `deployed` check because when you test locally transactions are mined synchronously and immediately. The Hardhat section does include `deployed` so I'm going to close this issue.
