### ISSUE TITLE
How can I integrate to forge project?

### ISSUE THREAD

**Issue by qiluge** [OpenZeppelin/openzeppelin-upgrades#570]
Hello, I'm using [forge](https://github.com/foundry-rs/foundry) to develop a project. I've been using hardhat before. I have a good experience with the hardhat upgrades plug-in. I hope to know how to use the upgrades plug-in in the forge framework.

**Comment by qiluge** [comment]
Hardhat and forge could coexist, so use hardhat at your forge project directly...

**Comment by frangio** [comment]
Unfortunately the project is not compatible with forge at the moment.

**Comment by leonwilly** [comment]
I'm working on changing that!
