### ISSUE TITLE
BUG - Wrong incompatible storage layout error

### ISSUE THREAD

**Issue by sullof** [OpenZeppelin/openzeppelin-upgrades#572]
I am trying to upgrade an NFT contract.
The original one (https://github.com/ndujaLabs/everdragons2-core/blob/main/contracts/Everdragons2Genesis.sol#L28)  has the variables:
```
  bool private _mintEnded;
  bool private _baseTokenURIFrozen;
  string private _baseTokenURI;

  address public manager;
  ```
The V2 (https://github.com/ndujaLabs/everdragons2-core/blob/main/contracts/mocks/Everdragons2GenesisV2Mumbai.sol#L26) has
```
  bool private _mintEnded;
  bool private _baseTokenURIFrozen;
  string private _baseTokenURI;

  address public manager;

  mapping(address => bool) public pools;
  mapping(uint256 => address) public staked;
```
Since `pools` and `staked` are added after `manager`, the storage should be compatible.
In fact, all tests pass. 

But, trying to upgrade the contract on Mumbai, I get an error:
```
$ bin/deploy.sh upgradeE2Mumbai mumbai
Deploying contracts with the account: 0x34923658675B99B2DB634cB2BC0cA8d25EdEC743 to mumbai
Account balance: 7585303523419268809
Error: New storage layout is incompatible

Everdragons2Genesis: Deleted `manager`
  > Keep the variable even if unused

contracts/mocks/Everdragons2GenesisV2Mumbai.sol:30: Inserted `manager`
  > New variables should be placed after all existing inherited variables
```
This error does not make sense.
In fact, it suggest to keep the variable `manager` (which has not been deleted) and later says that `manager` has been inserted.

**Comment by sullof** [comment]
BTW, using the same script to upgrade the proxy on localhost works without any issue.

**Comment by sullof** [comment]
Since we have some rush, I tried to workaround the issue. After a few attempts, I was finally able to upgrade the proxy after 

1. removing the `.openzeppelin` folder and 
2. register the deployed proxy for upgrading using `forceImport`.

I am not closing the issue, just in case you want to investigate, or take notes for the future.
Feel free to close it.

**Comment by sullof** [comment]
It is all in the repo linked above.
Unfortunately, when I removed the `.openzeppelin` folder I didn't think of saving it somewhere. I guess that that would come useful.

**Comment by frangio** [comment]
Closing as it will be hard or impossible to reproduce the issue.

As a side note, you should be committing `.openzeppelin/` into your git repository.

**Comment by sullof** [comment]
@frangio Thanks Francisco. I was committing it. I removed it because of that problem. When I am sure that it is stable, I will commit it again.
