### ISSUE TITLE
Dry-run mode in prepareUpgrade

### ISSUE THREAD

**Issue by kargakis** [OpenZeppelin/openzeppelin-upgrades#573]
Currently, if we want to dry-run an upgrade just to validate it we have to stitch together logic from `prepareUpgrade` which is cumbersome as there is a lot of conditional code that is already in place. It would be nice to enable dry-running `prepareUpgrade` to allow for more robust processes downstream. The other workaround for now is to run in forking mode and have custom logic that copies the network file at the right place which is also not ideal.

**Comment by ericglau** [comment]
https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/580 will cover this use case with a different approach.

Closing this issue as described in https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/578#issuecomment-1133323217
