### ISSUE TITLE
Update documentation to mention _disableInitializer()

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-upgrades#574]
Update https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializing_the_implementation_contract to mention that when using Contracts v4.6.0 or later, the constructor should call [`_disableInitializers()`](https://docs.openzeppelin.com/contracts/4.x/api/proxy#Initializable-_disableInitializers--)

**Comment by Amxx** [comment]
Closed by #575

**Comment by taochen2001** [comment]
when adding the following to a upgradeable contract, it cannot be compiled by hardhat; Can you look into this? I got compilation error DeclarationError: Undeclared identifier. It seems compiler is not recognizing  the function _disableInitializers().
-------------
constructor() {
       _disableInitializers();
    }

**Comment by ericglau** [comment]
@taochen2001 Which version of `@openzeppelin/contracts-upgradeable` are you using?  `_disableInitializers()` was introduced in v4.6.0

**Comment by taochen2001** [comment]
Just checked, it is "version": "4.5.2". Shall I upgrade to v4.6.0? By the way, in the current 4.5.2 version, even if I imported the ReentrancyGuardUpgradeable.sol in my contract, nonReentrant modifier won't be recognized by the compiler (using Hardhat); not sure if this is a bug or not.

**Comment by taochen2001** [comment]
Now i upgraded to V4.6.0, but got the following error during compiling:
Error: Contract `Token` is not upgrade safe

contracts/Token.sol:12: Contract `Token` has a constructor
    Define an initializer instead

**Comment by taochen2001** [comment]
It is now working after adding: 
    /// @custom:oz-upgrades-unsafe-allow constructor

**Comment by gabkov** [comment]
the solution provided by @taochen2001 is the only one? seems like a workaround. 

` "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "@openzeppelin/hardhat-upgrades": "^2.0.0",`

**Comment by catellaTech** [comment]
> Update https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializing_the_implementation_contract to mention that when using Contracts v4.6.0 or later, the constructor should call [`_disableInitializers()`](https://docs.openzeppelin.com/contracts/4.x/api/proxy#Initializable-_disableInitializers--)

I would like to know if, with this method, it is not recommended to implement any logic in the constructor and instead only do so in the initialize function. What is the difference when using it in a proxy? For example, I have a contract that will be a proxy, and I implement it like this:

```solidity
constructor(IValidator _validator) {
        validator = _validator; 
        _disableInitializers();
    }

    /**
     * @dev Initializes the contract, setting up roles and initial state.
     * @param _initialOwner Address of the initial owner (granted DEFAULT_ADMIN_ROLE)
     */
    function initialize(address _initialOwner) public initializer {
        __ERC20_init("Dollar", "USD");
        __ERC20Pausable_init();
        __ERC20Permit_init("Dollar");
        __AccessControl_init();
        __UUPSUpgradeable_init();

        _grantRole(DEFAULT_ADMIN_ROLE, _initialOwner);
    }
```
I have audited major protocols that don’t follow this approach, but I’ve seen cases where projects are not interested in pursuing what seems to be the safest route, such as implementing and setting the logic in the `initialize` function and only leaving `_disableInitializers()` in the constructor. I still have doubts though, and if someone could help me understand this better, I would greatly appreciate it.
