### ISSUE TITLE
TypeError: Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by CVRD-Dev** [OpenZeppelin/openzeppelin-upgrades#576]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

TypeError: Cannot read property 'layout' of undefined when trying to deploy contract for test using truffle-upgrades.deployProxy

## Expected Behavior
Contract is deployed to unit test

## Actual Results

An error is returned:
`TypeError: Cannot read property 'layout' of undefined` and the contract is not deployed

![Capture](https://user-images.githubusercontent.com/77033904/167651228-89db0b02-acd4-4d80-b292-e936a3afd414.PNG)

contract code
```
contract AeonERC1155 is Initializable, ERC1155Upgradeable, OwnableUpgradeable, PausableUpgradeable, ERC1155BurnableUpgradeable, ERC1155SupplyUpgradeable {
/// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    uint16 aeonPercentage;


    function initialize() initializer public {
        __ERC1155_init("");
        __Ownable_init();
        __Pausable_init();
        __ERC1155Burnable_init();
        __ERC1155Supply_init();
        //initialize the aeon percentage be 2.5%
         aeonPercentage = 250;
    }
}
```

test code
```
const AeonInstance = artifacts.require("AeonERC1155");
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');

describe('upgrades', () => {
  it('works', async () => {
    const instance =  await deployProxy(AeonInstance, [421]);
  });
});
```

Another thing to note is that I am able to successfully migrate this contract using the `truffle-upgrades.deployProxy` logic, but the same logic fails when trying to deploy for test.

migrate code
```
const Migrations = artifacts.require("Migrations");
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');
const AeonInstance = artifacts.require("AeonERC1155");

module.exports = function (deployer) {
  const instance =  deployProxy(AeonInstance, [42], { deployer });
};
```

## Environment

* Operating System: windows 10
* Truffle version (`truffle version`): v5.5.13
* node version (`node --version`): v14.17.6
* npm version (`npm --version`): 6.14.15
* the latest versions of contract-upgradeable & truffle-upgrades

**Comment by ericglau** [comment]
Hi @CVRD-Dev,

Would you be able to share a repo that can be used to reproduce this?  

The contract code doesn't match your test/migrate code, since that contract does not take any initializer variables.  Could you try running `truffle compile --all` and then try `truffle test` again?

**Comment by rishalAccubits** [comment]
Iam facing the same issue. First time truffle migrate --reset run success and contracts are deployed.

**Comment by frangio** [comment]
Please share a repository where we can reproduce the problem.

**Comment by rishalAccubits** [comment]
the issue was resolved. it was my mistake that i tried connecting the contracts to remix using remixd command from terminal. so there were multiple folders generated at compilation. removing that fixed my issue. Thanks
