### ISSUE TITLE
@openzeppelin/hardhat-upgrades v1.18 has a conflict with @nomiclabs/hardhat-etherscan

### ISSUE THREAD

**Issue by tempe-techie** [OpenZeppelin/openzeppelin-upgrades#586]
The `hardhat-upgrades` package version 1.18.0 has a conflict with `@nomiclabs/hardhat-etherscan` which produces the following error:

```bash
Error HH210: Redefinition of task verify failed. Unsupported operation adding positional param definitions in an overridden task.
```

Packages version:

- `@openzeppelin/hardhat-upgrades`: `1.18.0`
- `@nomiclabs/hardhat-etherscan`: `3.0.4` (but the problem persists with lower versions too (2.x.x))

### Solution

Downgrading `@openzeppelin/hardhat-upgrades` to version `1.12.0`.

**Comment by ericglau** [comment]
Hi @tempe-techie,

To get around this error, can you try importing the `@nomiclabs/hardhat-etherscan` plugin before the `@openzeppelin/hardhat-upgrades` plugin in your Hardhat configuration?

If you are using JavaScript, import the plugins in the following order in hardhat.config.js:
```
require("@nomiclabs/hardhat-etherscan");
require("@openzeppelin/hardhat-upgrades");
```
Or if you are using TypeScript, import the plugins in the following order in hardhat.config.ts:
```
import "@nomiclabs/hardhat-etherscan";
import "@openzeppelin/hardhat-upgrades";
```

**Comment by tempe-techie** [comment]
Ha, interesting, this actually worked 😅 Thanks @ericglau!

**Comment by ericglau** [comment]
Thanks for confirming.  We should still fix the plugin to avoid this error.
