### ISSUE TITLE
Feature Request: Provide source code programmatically

### ISSUE THREAD

**Issue by ChrisBellew** [OpenZeppelin/openzeppelin-upgrades#587]
Hi there, thanks for providing such a useful set of contracts and tooling. I would like to express a request for a feature because I don't think there's any way to achieve what I need currently.

I'm using the `hardhat-upgrades` to deploy contracts. I now have a need to upgrade all of the contracts that have been deployed. I understand how to use the `deployProxy` and `upgradeProxy` methods but I'd like to write a unit test to confirm the process.

I would like the unit test to:
1. Deploy an old version of the contract source code using `deployProxy`
2. Test the old implementation behaviour
3. Upgrade to a new version of the source code using `upgradeProxy`
4. Test the new implementation behaviour

This implies that I have two versions of source code for the same contract i.e. the old code and the new code. My folder structure follows the typical hardhat structure of `/contracts`, `/artifacts` and `/cache`, but they are currently populated by the source, artifacts and cache of the *new* source code because that's what my application needs to use on an ongoing basis.

I'm having difficulty in step (1). I'm creating a contract factory by providing the ABI and the bytecode into `getContractFactory`. `deployProxy` fails with `The requested contract was not found. Make sure the source code is available for compilation`. I presume this is because it requires access to the *old* source code and I only have the *new* code available to validate against.

This seems to be an issue because of the tight coupling between hardhat's folder structure and the validation logic of hardhat-upgrades (possibly upgrades-core). What would be great if there was a way to provide the source code another way. Either by providing a different location as an override to `getContractFactory` or just passing in the source code directly. Then I can organise the old and new code separately and provide them separately.

Thanks for reading! Is there another way I am missing?

**Comment by ericglau** [comment]
Usually this is done by simply having different names for the old and new versions of your implementation.  e.g. MyContractV1 and MyContractV2.  Or if you really need to have the contract named the same for all versions, perhaps you could add older versions of your contract with different names for unit test purposes.

**Comment by ChrisBellew** [comment]
Thanks Eric. I'll do that instead.
