### ISSUE TITLE
Last example given in `Initializers` section of `Writing Upgradeable Contracts` does not compile

### ISSUE THREAD

**Issue by larryob** [OpenZeppelin/openzeppelin-upgrades#596]
It looks like the modifier on `initialize()` in `BaseContract` should be `onlyInitializing`.

```solidity
// contracts/MyContract.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

contract BaseContract is Initializable {
    uint256 public y;

    function initialize() public initializer {
        y = 42;
    }
}

contract MyContract is BaseContract {
    uint256 public x;

    function initialize(uint256 _x) public initializer {
        BaseContract.initialize(); // Do not forget this call!
        x = _x;
    }
}
```

**Comment by trubavuong** [comment]
Let's modify the pragma section to `pragma solidity ^0.8.0;`

**Comment by larryob** [comment]
> Let's modify the pragma section to `pragma solidity ^0.8.0;`

`^0.6.0` is the version used throughout the documentation (as seen [here](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializers) and [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/a3fcaa440f292ecbfe34fa3185b3d317e551e3db/docs/modules/ROOT/pages/writing-upgradeable.adoc))

The problem here seems to be that you can only use the `initializer` modifier once when using inheritance (see [here](https://forum.openzeppelin.com/t/uups-upgradeable-contractfactory-error-initializable-contract-is-already-initialized/28487/2)).
