### ISSUE TITLE
hardhat-defender does not allow setting `timeout` when calling `proposeUpgrade`

### ISSUE THREAD

**Issue by Remscar** [OpenZeppelin/openzeppelin-upgrades#609]
Using code like this:
```
const proposal = await hre.defender.proposeUpgrade(
    zAuctionProxyAddress,
    zAuctionFactory,
    {
      timeout: 5 * 60 * 1000,
    }
  );
 ```

Results in a compile error since `timeout` is not explicitly a member of `ProposalOptions`

Inspecting the source code of `proposeUpgrade` shows that any additional properties will be passed to the underlying `prepareUpgrade` call, however due to the way the `ProposalOptions` is defined, there is not a type safe way of passing in additional properties (unless we do a cast.)

**Comment by frangio** [comment]
For anyone working on this, note that it is only a type issue.
