### ISSUE TITLE
How to retrieve list of proxies managed by Beacon?

### ISSUE THREAD

**Issue by cormacncheese** [OpenZeppelin/openzeppelin-upgrades#615]
I am using the Beacon proxy upgrade pattern as [outlined here](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/README.md):

```
 const beacon = await upgrades.deployBeacon(Box);
 await beacon.deployed();
 const box = await upgrades.deployBeaconProxy(beacon, Box, [42]);
```

How do you get a list all the beacon proxies deployed from your beacon? Typically this is stored on-chain in a factory

**Comment by ericglau** [comment]
[Answered in forum post](https://forum.openzeppelin.com/t/get-list-of-proxies-managed-by-beacon/30630/2?u=ericglau).
