### ISSUE TITLE
Support specifying an upgrade function and parameters in upgradeProxy

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-upgrades#62]
Need a mechanism to be able to initialize state when upgrading so that it is part of the upgrade transaction.  
Otherwise users would need to protect with some form of access control so they could do this in a separate transaction.

For example, adding a new state variable `otherValue` in version 2 and needing a safe way to initialize it on upgrade.
```solidity
    function upgradeV2(uint256 initialValue) public {
        require (!_upgradeV2, "Box: already upgraded to V2");
        _upgradeV2 = true;
        
        otherValue = initialValue;
    }
```

**Comment by abcoathup** [comment]
Additionaly in docs we should provide an example of using an upgrade function and how to appropriately guard it so that it is only called once.  

There have been two recent issues in the forum where community members have tried to protect an upgrade function with the `initializer` modifer.

* https://forum.openzeppelin.com/t/error-upgrading-smart-contracts/3679
* https://forum.openzeppelin.com/t/add-new-state-variable-to-base-contract-for-upgradeable-contracts/3502

Example of a guarded upgrade: https://forum.openzeppelin.com/t/error-upgrading-smart-contracts/3679/2?u=abcoathup

**Comment by pasevin** [comment]
Hi, is this still the case with UUPSUpgradeable?
