### ISSUE TITLE
deployProxy does not allow to run initilize on implementation without args

### ISSUE THREAD

**Issue by FredCoen** [OpenZeppelin/openzeppelin-upgrades#624]
If the initialize function on the logic contract takes no args there is no way to call it anyway with deployProxy. The docs mention as long as args [] is supplied to deployProxy it should run the initialize() function (https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#deploy-proxy). However if this array is empty it doesnt run it. This should not behave like this right?

**Comment by ericglau** [comment]
In this case, it should attempt to run the `initialize()` function by default, but won't fail if it's not found.  If you want to enforce running an initializer, you can pass in the initializer function as an option e.g. `await upgrades.deployProxy(MyContract, { initializer: 'initialize()' });`

**Comment by ericglau** [comment]
The initializer will be called as part of the same transaction where the proxy was deployed.  You should see events emitted in that transaction (e.g. for [`OwnershipTransferred`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/access/OwnableUpgradeable.sol#L86)).

With an empty array, it still runs the `initialize()` if it is available.  The docs could be improved to clarify that.

**Comment by FredCoen** [comment]
interesting how do you do that in the same transaction? i mean contract creation and calling the initialize()?

**Comment by ericglau** [comment]
The [proxy contract's constructor](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/proxy/ERC1967/ERC1967Proxy.sol#L23) calls [`_upgradeToAndCall`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/proxy/ERC1967/ERC1967Upgrade.sol#L65), which sets the implementation address and does a delegate call to the initializer.
