### ISSUE TITLE
Specify signer 

### ISSUE THREAD

**Issue by FredCoen** [OpenZeppelin/openzeppelin-upgrades#631]
Is there a way to pick a different signer address than account 0 with deployProxy or upgradeProxy?

**Comment by ericglau** [comment]
You can connect your ethers contract factory to a different signer.  See https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85#issuecomment-1028435049 for an example.

**Comment by ericglau** [comment]
I'd also suggest posting on the [forums](https://forum.openzeppelin.com/c/support/upgrades/35) if you have general questions such as these, and keep GitHub issues for specific feature requests or bug reports.

**Comment by frangio** [comment]
Closing as duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85.
