### ISSUE TITLE
`bool` to `uint8` variable upgrade is not allowed

### ISSUE THREAD

**Issue by jjranalli** [OpenZeppelin/openzeppelin-upgrades#640]
From [this issue](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3092) it seems like it should be possible upgrading a variable from `bool` to `uint8` without triggering a `New storage layout is incompatible` error.

However, the error is being triggered and only workaround at the moment seem to be enabling the `unsafeSkipStorageCheck` flag.

Minimal repo to reproduce the issue: https://github.com/jjranalli/hardhat-upgradeable-storage-issue

@frangio

**Comment by frangio** [comment]
Changing from bool to uint8 is not allowed by default, you need to enable it with a comment in the source code:

```
/// @custom:oz-retyped-from bool
uint8 x;
```

I thought you were asking about Initializable.sol, which includes this flag as seen [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/dc14c72e534183c20459e0cf47f00b59afb17a66/contracts/proxy/utils/Initializable.sol#L60).

Make sure to read the entry in the FAQ: [How can I rename a variable, or change its type?](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename)
