### ISSUE TITLE
Provide a way to set gas price when deploying proxy

### ISSUE THREAD

**Issue by iners-max** [OpenZeppelin/openzeppelin-upgrades#644]
Currently there is no way to set `gasPrice`, `maxFeePerGas` and `maxPriorityFeePerGas` when deploying a proxy using ContractFactory.deployProxy().

**Comment by frangio** [comment]
Duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85.

See https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85#issuecomment-1028435049 for a workaround.
