### ISSUE TITLE
Better support Hardhat tests in --parallel mode

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#645]
In Parallel mode, each thread gets its own Hardhat Network instance, yet they all have the same chain id so they use the same manifest file. I don't think this will cause errors with the manifest file because due to being a development network we basically ignore the contents if they don't match expectations, but it will for sure cause unnecessary contention and lead to errors such as https://github.com/NomicFoundation/hardhat/discussions/3093. 

This should probably be fixed along with https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/465, by detecting different instances and using a different manifest file for each.

**Comment by frangio** [comment]
Note: There is currently no built-in way to uniquely identify Hardhat Network instances. We could use `process.pid` as a workaround untill that exists.

**Comment by Ramarti** [comment]
+1
```
  2) Forta
       "before all" hook for "check deployment":
     Error: Lock file is already being held
      at /home/somedude/workspace/forta-token/node_modules/proper-lockfile/lib/lockfile.js:68:47
      at callback (node_modules/graceful-fs/polyfills.js:306:20)
      at FSReqCallback.oncomplete (node:fs:199:5)

```

**Comment by frangio** [comment]
There is now a way to implement this with the `hardhat_metadata` RPC method: https://github.com/NomicFoundation/hardhat/pull/3382.

Haven't found docs but here's the type that will be returned by the RPC method:

https://github.com/NomicFoundation/hardhat/blob/5cecb9692ca8bfa4a57a592e3233b24336da6e1c/packages/hardhat-core/src/internal/core/jsonrpc/types/output/metadata.ts
