### ISSUE TITLE
 Why is impossible to reuse mapping key at mapping(uint256=>EnumberableSet.AddressSet)?

### ISSUE THREAD

**Issue by DedicatedDev** [OpenZeppelin/openzeppelin-upgrades#649]
I've defined one state variable called data that has mapping(uint256=>EnumberableSet.AddressSet),
according to the requirements, I've deleted item like this.
delete data[0]

after delete, if I try to add one variable again with this key -> 0
data[0].add(msg.sender), no runtime error but happened nothing at variable data.
it maintain original values and don't save.
If faced on such trouble past time, could kindly teach me to solve this?
best.

**Comment by frangio** [comment]
Discussed in the forum: https://forum.openzeppelin.com/t/why-is-impossible-to-reuse-mapping-key-at-mapping-uint256-enumberableset-addressset/31688

**Comment by DedicatedDev** [comment]
yeah. it's me. ;)
