### ISSUE TITLE
Problems with storage layout check in v1.19.1

### ISSUE THREAD

**Issue by Ramarti** [OpenZeppelin/openzeppelin-upgrades#653]
Hi, I'm having problems with the new storage layout checks (supporting __gap array changes).
In previous versions I would skip the storage check and go by hand. This time I upgraded in testnet 5 contracts without issue, then having messages that seem erroneous to me.

New implementation
https://github.com/forta-network/forta-contracts/blob/deploy/v1_1_0/contracts/components/staking/FortaStakingParameters.sol

Old implementation
https://mumbai.polygonscan.com/address/0x1837cf2b32b25b6ddb4d8d004b3dc423d1d72243#code
Proxy: https://mumbai.polygonscan.com/address/0x2441Ce5eB269505f30F6F434D21E039438aaC342#code

Output Message
```
Error: New storage layout is incompatible

ERC1967UpgradeUpgradeable: Deleted `__gap`
  > Keep the variable even if unused

ERC1155Upgradeable: Deleted `_balances`
  > Keep the variable even if unused

ERC1155Upgradeable: Deleted `_operatorApprovals`
  > Keep the variable even if unused

ERC1155Upgradeable: Deleted `_uri`
  > Keep the variable even if unused

ERC1155Upgradeable: Deleted `__gap`
  > Keep the variable even if unused

ERC1155SupplyUpgradeable: Deleted `_totalSupply`
  > Keep the variable even if unused

ERC1155SupplyUpgradeable: Deleted `__gap`
  > Keep the variable even if unused

FortaStaking: Deleted `stakedToken`
  > Keep the variable even if unused

FortaStaking: Deleted `_activeStake`
  > Keep the variable even if unused

FortaStaking: Deleted `_inactiveStake`
  > Keep the variable even if unused

FortaStaking: Deleted `_lockingDelay`
  > Keep the variable even if unused

FortaStaking: Deleted `_rewards`
  > Keep the variable even if unused

FortaStaking: Deleted `_released`
  > Keep the variable even if unused

FortaStaking: Deleted `_frozen`
  > Keep the variable even if unused

FortaStaking: Deleted `_withdrawalDelay`
  > Keep the variable even if unused

FortaStaking: Deleted `_treasury`
  > Keep the variable even if unused

contracts/components/staking/FortaStakingParameters.sol:9: Renamed `_stakingParameters` to `_fortaStaking`

contracts/components/staking/FortaStakingParameters.sol:11: Replaced `__gap` with `_stakeSubjectHandlers` of incompatible type
```

It seems weird that is worrying about FortaStaking, since FortaStakingParameters does not inherit from it, it's the type of a property.

I'm using a homebrewed tool to map the layout transitions, extracting the storage values from the plugin's `.openzeppelin files`. It outputs this:

| BEFORE |   |   |   | AFTER |   |  |
| -- | -- | -- | -- | -- | -- | -- |
| Initializable | _initialized | 1 | | Initializable | _initialized | 1 |
| Initializable | _initializing | 1 | | Initializable | _initializing | 1 |
| ContextUpgradeable | __gap | 50 | | ContextUpgradeable | __gap | 50 |
| AccessManagedUpgradeable | _accessControl | 1 | | AccessManagedUpgradeable | _accessControl | 1 |
| AccessManagedUpgradeable | __gap | 49 | | AccessManagedUpgradeable | __gap | 49 |
| RoutedUpgradeable | _router | 1 | | RoutedUpgradeable | _router | 1 |
| RoutedUpgradeable | __gap | 49 | | RoutedUpgradeable | __gap | 49 |
| ERC1967UpgradeUpgradeable | __gap | 50 | | ERC1967UpgradeUpgradeable | __gap | 50 |
| UUPSUpgradeable | __gap | 50 | | UUPSUpgradeable | __gap | 50 |
| BaseComponentUpgradeable | __gap | 50 | | BaseComponentUpgradeable | __gap | 50 |
| FortaStakingParameters_0_1_0 | _fortaStaking | 1 | | FortaStakingParameters | _fortaStaking | 1 |
| FortaStakingParameters_0_1_0 | _stakeSubjectHandlers | 1 | | FortaStakingParameters | _stakeSubjectHandlers | 1 |
|  | total | 304 | |  | total | 304 |

Which should be fine to upgrade

**Comment by ericglau** [comment]
This looks like the wrong contracts are being compared.  Can you share what script and/or command you are using that encounters this error?

I tried the following Hardhat script to run the validations between the old implementation on Mumbai and the new implementation (using `@openzeppelin/hardhat-upgrades@1.20.0`), and the validations passed:
```
const { upgrades } = require("hardhat");

async function main() {
  const NewVersion = await ethers.getContractFactory('FortaStakingParameters');
  await upgrades.validateUpgrade('0x1837CF2B32B25B6dDb4d8D004B3DC423d1d72243', NewVersion, {constructorArgs: ['0x0000000000000000000000000000000000000000'], kind: 'uups', unsafeAllow: ['delegatecall'] });
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by Ramarti** [comment]
You are absolutely right, there's a bug on my script and it was getting the address from a contract with a similar name.
Thanks!
