### ISSUE TITLE
hardhat-upgrade: TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by longdieu12x** [OpenZeppelin/openzeppelin-upgrades#655]
Hi i face this error when trying to use hardhat-upgrades, anyone can help me to know what problem is happening here ? Currently, I think it is just because of conflicting version between hardhat-toolbox and hardhat-upgrades
![image](https://user-images.githubusercontent.com/74671798/190046812-22bd5be5-787e-4916-b137-bfea7685e921.png)
![image](https://user-images.githubusercontent.com/74671798/190046888-1ca28d12-df71-4f73-bb14-f686f5e7136f.png)
![image](https://user-images.githubusercontent.com/74671798/190046911-b3017590-ef42-4061-8933-d0c322ae1f4d.png)

**Comment by frangio** [comment]
Do you still have this error?

**Comment by BoZhao1992** [comment]
Did you solve it?
