### ISSUE TITLE
Support configuration of .openzeppelin directory path

### ISSUE THREAD

**Issue by AboldUSER** [OpenZeppelin/openzeppelin-upgrades#672]
Our organization uses Hardhat for deployment across multiple private chains, and configures the paths of Hardhat's inputs and outputs (https://hardhat.org/hardhat-runner/docs/config#path-configuration) into folders not necessarily in the project's directory.

Currently the .openzeppelin directory is created in the root of where the oz-upgrades scripts are called from, at least when using the Hardhat plugin. This is due to the openZeppelin-upgrades directory being hardcoded as '.openzeppelin' in the core package's file [./packages/core/src/manifest.ts](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/manifest.ts#L41), and that string is defined as the .openzeppelin path in the [manifest.ts constructor](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/src/manifest.ts#L58).

I'd like to have optional configuration of the manifest directory path, with a default to the current manifestDir string, '.openzeppelin', similar to how Hardhat handles configuration of its paths.

A possible solution would be to pass an optional parameter into the manifest.ts constructor that defines the manifest path for the this.fallbackFile and this.file variables, and falls back to the default path if the parameter is not passed/null. This passing of path data can be similar to how the manifest.ts constructor currently takes the chainId, which comes from the deployData object defined in the plugin packages. In the Hardhat plugin, when creating the deployData object in [getDeployData function](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/utils/deploy-impl.ts#L41), another const can be added that reads the hre object for a path defined in the hardhat.config file, such as 'hre.config.ozUpgrades.manifestPath'. I am assuming something similar can be done with the Truffle plugin.

**Comment by frangio** [comment]
You included a lot of details about how this would be implemented, but we should focus on what this is going to look like for the end-user.

We currently don't have any global configuration (in hardhat.config.js) so I'd try to avoid that. Would it be sufficient to include it as an option in functions like `deployProxy`? `deployProxy(..., { ..., manifest: 'path/to/manifest.json' })`

**Comment by AboldUSER** [comment]
My initial thought on the hardhat.config file was because that's how I'm use to using other hardhat plugins. I guess I let my tool bias drive the above 😅

Setting an option in a config to me means it only has to be set once, though I agree that if the other existing oz-upgrades configurations are tied to function calls then best to stick with that pattern for consistency. The user will need to ensure they pass the optional parameter for each deploy/upgrade function. Keeping it as a function's optional parameter will probably be easier to manage across multiple dev tools as well (HardHat, Truffle, future tools).

**Comment by frangio** [comment]
@ericglau what's your opinion on this?

**Comment by ericglau** [comment]
I think it makes sense to introduce a global configuration for this scenario.  The existing options for function calls are specific to those functions, but the manifest path is something that should be common between all functions.  Having the manifest path as a function option could cause problems if users forget to specify the custom path in some functions (for example, that may lead to redeploying an implementation unnecessarily, or a proxy being registered in the wrong manifest location).

In terms of how to specify the global config, we could use the native configuration method for each dev environment (Hardhat or Truffle config file as suggested above) and/or fallback to look for an environment variable.  The environment variable fallback could possibly help with supporting this in future tools.  @frangio, any thoughts on the environment variable approach?

**Comment by frangio** [comment]
Environment variable as fallback sounds good to me.
