### ISSUE TITLE
Verify UpgradeableBeacon.sol after using upgrades.deployBeacon()

### ISSUE THREAD

**Issue by karacurt** [OpenZeppelin/openzeppelin-upgrades#677]
I was not able to verify a UpgradeableBeacon.sol  after deploy it on polygon-mumbai using upgrades.deployBeacon. After a lot of attempts, i tried to create a contract that extends a UpgradeableBeacon.sol.  After that i was able to verifiy, but that doesn’t work for me, i need to use upgrades.deployBeacon() in order to also deploy the implementation contract for me. Any ideas of what could it be? 

Obs: I've also tried to create a flatten file of UpgradeableBeacon.sol to verify as a single file on polygonscan, but it didn’t work.

**Comment by ericglau** [comment]
What kind of error are you getting?

Did you try using the Hardhat Upgrades plugin's `verify` task? See https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#verify - you can pass in the beacon proxy address, and that will verify all of the related contracts including the UpgradeableBeacon.

**Comment by karacurt** [comment]
I got that the byte code was not found. 

That's the address i'm trying to verify: 
https://mumbai.polygonscan.com/address/0x01A0c03311259c7e1E54942d27be07078362E0c0

I've also tried to use hardhat's verify task, but throws an error that also didn’t found any bytecode in the repository that matches with the code in the address.

I see that there is more 29 codes with the same bytecode in mumbai that is not verified.

**Comment by ericglau** [comment]
I'm not sure what the issue was, but I just tried deploying an UpgradeableBeacon and BeaconProxy on Mumbai and was able to verify it using the task.  So that means your address is also verified now (with Similar Match Source Code).  

For reference, I used this script to deploy:
```
import { ethers, upgrades } from "hardhat";

async function main() {
  const ContractFactory = await ethers.getContractFactory("MyToken");

  const beacon = await upgrades.deployBeacon(ContractFactory);
  await beacon.deployed();

  console.log(`Beacon deployed to ${beacon.address}`);

  const proxy = await upgrades.deployBeaconProxy(beacon, ContractFactory);

  console.log(`Proxy deployed to ${proxy.address}`);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```

Then set up the verify task according to [these steps](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#verify), and ran `npx hardhat verify --network mumbai <beacon proxy address from above>`

**Comment by ericglau** [comment]
Closing this issue but feel free to comment if you have further related questions.

**Comment by karacurt** [comment]
Thank you @ericglau,

I just need to understand better. I'm just able to verify a UpgradeableBeacon.sol with i deploy a BeaconProxy.sol with it?

Can't i just verify the UpgradeableBeacon alone?

**Comment by ericglau** [comment]
You should be able to verify an UpgradeableBeacon manually by following [this post](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225#if-proxy-is-not-verified-10) (by submitting the Solc json input file to etherscan/polygonscan).

The `verify` task in the hardhat-upgrades plugin currently needs a proxy address as its argument.  For a beacon proxy, that would verify the beacon proxy itself and any associated contracts (including the UpgradeableBeacon).

**Comment by karacurt** [comment]
Thank you for clarifying @ericglau !!
