### ISSUE TITLE
Is there benefit to use "Explicit Storage Buckets" in OZ's UUPS?

### ISSUE THREAD

**Issue by Andriy-Kulak** [OpenZeppelin/openzeppelin-upgrades#701]
I am using OZ's `UUPSUpgradeable` package in Solidity 0.8.17 and my question is around best practices.

I found that some people recommend `Explicit Storage Buckets` for private variable, reference dragonfly [docs](https://github.com/dragonfly-xyz/useful-solidity-patterns/tree/main/patterns/explicit-storage-buckets)

However since I am using  `UUPSUpgradeable` on top of `@openzeppelin/hardhat-upgrades` to deploy my UUPS. This automatically checks for variable collision when I upgrade using `deployProxy` in hardhat, so are explicit storage buckets necessary?

In seems to add extra code, so I would prefer to keep it out unless there is additional benefits. Only benefit I can think of would be additional safety is upgrades don't happen with hardhat-upgrade's `deployProxy'. Do y'all have any feedback?

**My Environment:**
- solidity 0.8.17
- latest hardhat
 "@openzeppelin/contracts-upgradeable": "^4.8.0",
 "@openzeppelin/hardhat-upgrades": "^1.21.0",

**Comment by ericglau** [comment]
Answered in [forum thread](https://forum.openzeppelin.com/t/is-there-benefit-to-use-explicit-storage-buckets-in-ozs-uups/33705/2). To be addressed by https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/459 although details of the expected pattern are to be determined.
