### ISSUE TITLE
Support gap resizing in Truffle

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#709]
Gap resizing is currently only available on Hardhat, due to storage layout information from the compiler being only available on Hardhat. We don't want to compute the storage layout info ourselves because there is a risk we might implement a different algorithm to the Solidity compiler, so we are blocked on this issue until Truffle exposes the entire compiler output.

**Comment by ericglau** [comment]
Closing as Truffle is deprecated
