### ISSUE TITLE
Compilation warnings in test contracts

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-upgrades#723]
From this repository's `packages/core` directory, run `yarn`.  The following compilation warnings occur:
```
$ tsc -b && yarn compile:contracts
$ hardhat compile && node scripts/copy-build-info.js
Warning: Return value of low-level calls not used.
 --> contracts/test/ignore-errors/Constructors.sol:7:9:
  |
7 |         msg.sender.delegatecall(data);
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: Return value of low-level calls not used.
  --> contracts/test/ignore-errors/Constructors.sol:25:9:
   |
25 |         msg.sender.delegatecall('');
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: Return value of low-level calls not used.
  --> contracts/test/ignore-errors/Constructors.sol:46:9:
   |
46 |         msg.sender.delegatecall('');
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: Return value of low-level calls not used.
  --> contracts/test/ignore-errors/Constructors.sol:79:9:
   |
79 |         msg.sender.delegatecall('');
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: Return value of low-level calls not used.
 --> contracts/test/ignore-errors/Modifiers.sol:7:9:
  |
7 |         msg.sender.delegatecall(data);
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Compiled 79 Solidity files successfully
```

These contracts are used for tests only, but either find a way to ignore these specific warnings, or update the test cases to not cause these.

Ensure that the tests still pass when running `yarn test`.

**Comment by frangio** [comment]
See my Hardhat plugin: [hardhat-ignore-warnings](https://github.com/frangio/hardhat-ignore-warnings)

**Comment by sujantkumarkv** [comment]
Hey, these are my findings:

The warnings are related to `delegatecall`, it's used to execute code from another contract, and returns the value that is returned by the called contract. However, the return value here is not being used, hence causing the warnings.

To fix this, we can either store the return value of `delegatecall` in a variable and use it somehow or we can use the "call" function instead which allows for code execution from another contract, but it does not return a value.

Is a return value something that's necessary for the tests? i'll proceed based on your inputs.

**Comment by sujantkumarkv** [comment]
I have opened a pull request for this issue, [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/730).
