### ISSUE TITLE
Offer a way to safely rename state variables across upgrades

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#73]
State variable renaming is not allowed for upgrades, because it could have actually been an error by the user which implies a storage layout change.

We should offer a way to rename anyway. My preference would be a way for developers to explicitly mark a state variable as being a rename of the previously existing variable in the same storage location. Something like...
```solidity
string private admin; // formerly: owner
```

**Comment by evgenynacu** [comment]
@frangio this is nice feature to have
Currently there is workaround - you can just rename field in .openzeppelin/*.json 
Working good

**Comment by frangio** [comment]
Awesome suggestion @evgenynacu! Thanks.

---

Starting with Solidity 0.8.2 we could now implement this using `@custom` NatSpec tags:

```solidity
/// @custom:oz-upgrades-renamed-from owner
address private admin;
```

**Comment by NeoXtreem** [comment]
> Starting with Solidity 0.8.2 we could now implement this using `@custom` NatSpec tags:
> 
> ```solidity
> /// @custom:oz-upgrades-renamed-from owner
> address private admin;
> ```

Any idea when this will be implemented? It's causing a pain in my migrations where I have to hack my scripts to use @evgenynacu's workaround.

**Comment by frangio** [comment]
Sorry, no concrete plans right now.

**Comment by ericglau** [comment]
Resolved by https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/531

Available in the [latest version ](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fupgrades-core%401.14.0) of `upgrades-core`.  To update your installed package, use:
`npm install @openzeppelin/upgrades-core@latest`

For usage, see documentation at https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename
