### ISSUE TITLE
Version v1.x paths to contracts are broken 

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-upgrades#734]
## Description

Since reviewing the docs, I looked at [this page](https://docs.openzeppelin.com/upgrades-plugins/1.x/) and the first link is broken.
Also, the search for contracts is broken as well since it refers to v1.x pages.

The reason for this is that there's no v1.x page of OpenZeppelin contracts.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/1600135ab6588d44a3d56805eeed8554275bafa0.
