### ISSUE TITLE
Best practice for handling new package and solc versions

### ISSUE THREAD

**Issue by sanderpick** [OpenZeppelin/openzeppelin-upgrades#780]
These may be a obvious questions, but I don't see them covered anywhere... and considering the complexity and potential for pitfalls with upgrades, it would good to lay out some best practices for managing new package versions in existing projects.

- Is it safe to follow semantic versioning rules when adopting new versions of `@openzeppelin/hardhat-upgrades`? ie, can we assume that minor version bumps are backwards-compatible and major versions will not be? Or should we lock packages to their exact initial version forever?
- Is there any complexity here related to versioning of `@openzeppelin/contracts-upgradeable`?
- Is it okay to adopt new solc versions for implementation contracts, even though the proxy will always be locked to its initial compiler version?

Thank you!

**Comment by ericglau** [comment]
1. The package follows semantic versioning rules.  Minor version bumps are intended to be backwards-compatible.  (Occasionally a bug fix may require a breaking change if the original behaviour was considered a bug, but those will be documented in the [changelog](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/CHANGELOG.md))
2. Semantic versioning also applies.  e.g. a new major version of `@openzeppelin/contracts-upgradeable` would likely require changes in this plugin.
3. Yes, the solc version of implementation contracts does not need to be related to the solc version of the proxy.  The proxy contracts are precompiled by this plugin and packaged with the plugin [as seen here](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/25d1ba62c1ecb82b022982754b63c05b4ba416dc/packages/core/package.json#L8).

**Comment by sanderpick** [comment]
Great, thanks for the detailed answers @ericglau.
