### ISSUE TITLE
TransferProxyAdminOwnership in hardhat plugin does not support dynamic signer

### ISSUE THREAD

**Issue by icydark** [OpenZeppelin/openzeppelin-upgrades#782]
When calling TransferProxyAdminOwnership in the hardhat plugin, the function will attach the admin contract with the default hardhat account. I cannot use a dynamic signer to call the function in my script, which results in the error of 'caller is not owner'

**Comment by ericglau** [comment]
The manual workaround is to call `transferOwnership(newOwner)` on the admin contract directly.
