### ISSUE TITLE
Support scripts ran through `truffle exec`

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#81]
Depends on https://github.com/trufflesuite/truffle/issues/3221.

**Comment by chopachom** [comment]
Apparently global config is now available in scripts, is it possible to add support for it?

**Comment by frangio** [comment]
We should definitely do that if it's available. How did you hear that it's available now? Can you provide a reference?

**Comment by johhnsmmith198** [comment]
I can't believe there isn't support for truffle exec script yet!
This simple script:
```
let web3js = require("web3");
const { upgradeProxy, erc1967 } = require("@openzeppelin/truffle-upgrades");
const UpgradeablePet = artifacts.require("UpgradeablePet");
const UpgradeablePetV2 = artifacts.require("UpgradeablePetV2");

module.exports = async function (callback) {
  try {
    const instance = await UpgradeablePetV2.deployed();
    console.log(instance.address);
    console.log(erc1967);
    console.log(erc1967.getAdminAddress.toString());
    console.log(await erc1967.getAdminAddress(instance.address));
  } catch (error) {
    console.error(error);
  }
};
```
would fail with
```
Using network 'development'.

0x35B071769d63679C617110E6725F66B18e835181
{
  getAdminAddress: [Function (anonymous)],
  getImplementationAddress: [Function (anonymous)],
  getBeaconAddress: [Function (anonymous)]
}
(args, opts) => {
        const { deployer } = (0, _1.withDefaults)(opts);
        const provider = wrapProvider(deployer.provider);
        return getter(provider, args);
    }
Error: Global Truffle config not found: Truffle >=5.1.35 is required. Truffle exec not yet supported
```
removing the line `console.log(await erc1967.getAdminAddress(instance.address));` would make the script run correctly (but I havn't achieved anything)

**Comment by frangio** [comment]
The config object is still not available in `truffle exec` so this still doesn't work. However, a user proposed a workaround in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/761#issuecomment-1479396644

**Comment by ericglau** [comment]
Closing as Truffle is deprecated.
