### ISSUE TITLE
How can I create a Proxy Admin with a payable function?

### ISSUE THREAD

**Issue by AbhinavMir** [OpenZeppelin/openzeppelin-upgrades#815]
I want my proxy admin to have ETH for a niche usecase - how can I make this happen? I assume I have to use custom proxy, but I'm wondering if there is a way via Hardhat.

Thanks,
August.

**Comment by AbhinavMir** [comment]
Right, I just wanted to deposit some ETH into ProxyAdmin because a certain test case was failing and I wanted to make sure it wasn't because of it. Due to NDAs, don't think I can explain further :(

**Comment by ericglau** [comment]
In this case you would need a custom ProxyAdmin contract, which you would need to deploy and manage outside of the Hardhat Upgrades plugin.

**Comment by AbhinavMir** [comment]
Thanks, makes sense!
