### ISSUE TITLE
deployProxy fails on generic ERC1175 from open zepplin wizard

### ISSUE THREAD

**Issue by jblanchette-bb** [OpenZeppelin/openzeppelin-upgrades#825]
version: `1.17.0`

when running a migration in truffle that just calls `deployProxy` the following error has started appearing

```
hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.
```

Also the error does not say what the invalid op code was or where it was located.

None of the things it prints out are relevant as to why it failed

**Comment by frangio** [comment]
This error is generated by Truffle, not by the OpenZeppelin Upgrades plugin.

Please consider reporting it to Truffle directly.
