### ISSUE TITLE
Network files missing storage layout when overrides are used

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-upgrades#850]
The Hardhat Upgrades plugin normally enables storage layout automatically in Solidity compilation settings, so that detailed storage layout can be saved in the network files.

However, when a project's hardhat config has overrides for Solidity compiler settings (e.g. https://github.com/Idle-Labs/idle-tranches/blob/master/hardhat.config.js#L62), storage layout is not enabled for these overrides.  This causes the network file (such as https://github.com/Idle-Labs/idle-tranches/blob/master/.openzeppelin/unknown-1101.json#L496-L810) to be missing detailed storage layout such as `slot` and `offset` fields.  This causes storage layout checks to fail from storage gap resizing, even if the storage gap is being used properly.

--

Originally reported in https://forum.openzeppelin.com/t/bad-storage-gap-resize-when-adding-variables-and-reducing-gap/37196

**Comment by frangio** [comment]
This should be fixed in:

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/d1513992c58106b44967e42cb9f8cb2621d5a300/packages/plugin-hardhat/src/index.ts#L109-L118
