### ISSUE TITLE
Error when deploying an existing implementation twice - Hardhat

### ISSUE THREAD

**Issue by julianmrodri** [OpenZeppelin/openzeppelin-upgrades#877]
Hi, we are facing a strange error when calling `upgrades.deployImplementation()` for an implementation that already was deployed and registered in `mainnet.json`.  The error we get is the following:

![image](https://github.com/OpenZeppelin/openzeppelin-upgrades/assets/56316686/a44c49fa-cc0d-4604-951e-b916e603dae0)

A far as I understand, it should NOT do the deployment because it uses `onChange` by default, but it should not fail either and instead return the address of the deployed implementation. But for some reason is trying to process a transaction? 
This is our code that triggers the issue:

```
 const MainImplFactory = await ethers.getContractFactory('MainP1')
  let mainImplAddr =  (await upgrades.deployImplementation(MainImplFactory, {
      kind: 'uups',
    })) as string   
```
Works for the initial deployment, and works if the current code is not registered in the network file.

But once the deployed implementation is registered in the network file it fails the next time is run. If I simply remove the implementations from `mainnet.json` works smooth.

The error its manifesting when running against a local mainnet fork in this case. And also setting `redeployImplementation: always` does not fix the issue, exact same error. Also if I make a small change to the contract, it deploys it successfully.

Version: "@openzeppelin/hardhat-upgrades": "^1.23.0",
    
Any ideas what could be going on?

**Comment by julianmrodri** [comment]
@ericglau Sorry to tag you but would like to escalate this issue if possible as it is kind of blocking a mainnet deployment for us (not for the initial implementation but our deployment scripts are basically broken with this issue).  Any additonal info you need please let me know!! Thanks!!

**Comment by ericglau** [comment]
@julianmrodri Thanks for reporting this.  I was able to reproduce this issue and am looking into it.  Will let you know when I have an update.

**Comment by ericglau** [comment]
This issue appears to occur with certain RPC nodes when using a Hardhat forked network -- the `eth_getTransactionReceipt` RPC request causes an error when called with the tx hash of the original implementation deployment.

For example, the same error occurs by running the following RPC command locally:
`curl http://localhost:8545 -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, /' -H 'Cache-Control: no-cache' -X POST --data '{"jsonrpc": "2.0","id": 0,"method": "eth_getTransactionReceipt","params": ["<transaction hash of the original implementation deployment>"]}'`

@julianmrodri As a workaround, can you try a different RPC node when creating your forked network?  I encountered this issue when using a Hardhat forked network with Alchemy, but it worked when using Infura.

**Comment by julianmrodri** [comment]
I'll try with Infura. So this is only a fork issue? Would not behave like this if I rerun it against Mainnet for example?

**Comment by ericglau** [comment]
This appears to be an issue in Alchemy.  See https://github.com/NomicFoundation/hardhat/issues/4271

The plugin uses the tx hash to determine whether the contract deployment succeeded.  While we could consider a short-circuit in the plugin if there is already code at the expected address, this would only be a workaround and there could be other issues if the RPC is not behaving correctly.  The proper solution would be for Alchemy to fix the issue in their RPC response.

**Comment by julianmrodri** [comment]
Ok used Infura for this portion and seems to work. You can close the issue. Thanks!
