### ISSUE TITLE
Deploying with deployProxy doesn't set deployer as owner

### ISSUE THREAD

**Issue by veljkoTNFT** [OpenZeppelin/openzeppelin-upgrades#898]
I have this piece of code in my tests

```
//deploy factory
const Factory = await ethers.getContractFactory("Factory");
factoryContract = await upgrades.deployProxy(Factory, [token.target, someAddress]);
await factoryContract.waitForDeployment();

console.log("owner factory: " + await factoryContract.owner());
```

This prints out 0 address. I wanted to move to latest OZ v5 contracts and I have this issue in my tests. This same code works with 2.2.3 upgrades plugin and v4 of OpenZeppelin contracts. I'm using hardhat. Does anyone have this issue? Did something change in plugin, do I need to pass something more?

**Comment by ericglau** [comment]
OpenZeppelin Contracts 5.0 requires an [`initialOwner`](https://docs.openzeppelin.com/contracts/5.x/api/access#Ownable-constructor-address-) as an initializer argument for `Ownable`. 

In your initializer, you need to call
```
__Ownable_init(initialOwner);
```

See https://wizard.openzeppelin.com/ and select Ownable and enable Upgradeability for an example.

**Comment by veljkoTNFT** [comment]
It's completely unintuitive that you are inheriting Ownable2StepUpgraadeable and you don't call init of that contract, but you call it on contract that is one step further in inheritance line.

**Comment by ericglau** [comment]
@veljkoTNFT Thanks for the feedback.  I've opened https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4690 for further consideration, feel free to continue the discussion there.
