### ISSUE TITLE
Contract `_contract` is not upgrade safe. Implementation is missing a public `upgradeTo(address)` function

### ISSUE THREAD

**Issue by quiet-node** [OpenZeppelin/openzeppelin-upgrades#915]
So I have updated @Openzeppelin/contracts-upgradable from v4.x to the latest v.5.0.0, and when I try to deploy a proxy contract, I got this error

```bash
 Error: Contract `contracts/proxy-upgrade/exchange/Exchange.sol:Exchange` is not upgrade safe

contracts/proxy-upgrade/exchange/Exchange.sol:12: Implementation is missing a public `upgradeTo(address)` function
Inherit UUPSUpgradeable to include this function in your contract
@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol
https://zpl.in/upgrades/error-008
  at assertUpgradeSafe (node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:19:11)
  at validateImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/validate-impl.ts:42:20)
  at validateProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/validate-impl.ts:63:10)
  at deployProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:73:3)
  at Proxy.deployProxy (node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:45:28)
  at deployDEXProxyContract (test/proxy-upgrade/proxyUpgradeContracts.js:75:21)
  at Context.<anonymous> (test/proxy-upgrade/proxyUpgradeContracts.js:55:23)
```

Here is my setup: 

My `Exchange` contract has already inherited from the `@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol` like below:
```solidity
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";

contract Exchange is UUPSUpgradeable, OwnableUpgradeable {
...
}
```

Here is how I deploy it in my unit test: (Hardhat + Ethersjs + javascript)
```javascript
const { ethers, upgrades } = require('hardhat')
async function deployDEXProxyContract(token) {
      const contract = await ethers.getContractFactory(
        Constants.Contract.Exchange
      )

      const proxy = await upgrades.deployProxy(contract, [token], {
        kind: 'uups',
        initializer: 'initialize',
      })

      await proxy.deployed()

      return proxy
    }
```

I've noticed that in this [PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4382), the `upgradeTo` method has been removed from the UUPSUpgradable contract. Additionally, in this [FAQ question](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#why-public-upgradeto), it states that I need either `upgradeTo` or `upgradeToAndCall`. While `upgradeToAndCall` is still available in the `UUPSUpgradable`, I'm encountering an error. 

Is this a potential bug or something else?"

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ericglau** [comment]
Hi @quiet-node, `"@openzeppelin/hardhat-upgrades": "^2.3.0",` is the minimum version needed to work with OpenZeppelin Contracts 5.0, and it also requires ethers v6.

Would it be feasible for you to update your codebase to use ethers v6?

**Comment by quiet-node** [comment]
Hmm I'll see what our team can do about this! Thanks @ericglau for the comment!
