### ISSUE TITLE
@openzeppelin/hardhat-upgrades does not install with latest hardhat-toolbox

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [OpenZeppelin/openzeppelin-upgrades#932]
After the latest hardhat upgrade, the hardhat-toolbox library has a dependency conflict due to different versions of the verify package in the hardhat-upgrades and the hardhat-tool box libraries when trying to install hardhat-upgrades.

hardhat-upgrades library needs to be upgraded to the latest version of the verify package.

see PR #912  from renovate bot

**Comment by ericglau** [comment]
Thanks for raising this. We will likely make this change in hardhat-upgrades v3 which will be a major release (current alpha version available [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%403.0.0-alpha.0) does not include this yet).

**Comment by cryptobanksy** [comment]
`npm i -D @openzeppelin/hardhat-upgrades @nomicfoundation/hardhat-verify@^2.0 --force`

and  require` hardhat-upgrades` in `hardhat.config.js` 
`
require("@nomicfoundation/hardhat-toolbox");
require('@openzeppelin/hardhat-upgrades');
`

**Comment by ericglau** [comment]
We've released [@openzeppelin/hardhat-upgrades@3.0.0](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%403.0.0) which resolves this.
