### ISSUE TITLE
[Blockscout api issue] Proposal conditional calls 

### ISSUE THREAD

**Issue by eskrano** [OpenZeppelin/openzeppelin-upgrades#942]
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/6a89da4ee700aa9dcae96e669d93b7f8c38b8728/packages/plugin-hardhat/src/verify-proxy.ts#L227

Api call: https://docs.etherscan.io/api-endpoints/contracts#verifying-proxy-contract-using-curl

In case when using blockscout explorer im getting error for this call because its doesnt exists in blockscout api. 

```
Etherscan:
Etherscan API call failed with status 400, response: {"message":"Unknown action","result":null,"status":"0"}
```

Is there any solution to make this call optional?

**Comment by ericglau** [comment]
Hardhat Upgrades's `verify` task only supports Etherscan verification.  If you would like to verify on other block explorers, see https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225 for general steps.
