### ISSUE TITLE
How to upgrade the proxy using a gnosis multisig but without the defender admin client

### ISSUE THREAD

**Issue by haowang1013** [OpenZeppelin/openzeppelin-upgrades#946]
Hi,

We'd like to manage the contract upgrades with a gnosis multisig on a chain where the defender infrastructure is NOT running. Is this possible with the hardhat upgrades package? It seems the current implementation only supports interacting with gnosis via the defender admin API, is this correct?

Thanks

**Comment by ericglau** [comment]
You can use [prepareUpgrade](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#prepare-upgrade) to deploy the new implementation (which returns the new implementation's address), then submit a proposal through the multisig to call the proxy's `upgradeTo` or `upgradeToAndCall` function, passing in the new implementation's address.

**Comment by haowang1013** [comment]
> You can use [prepareUpgrade](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#prepare-upgrade) to deploy the new implementation (which returns the new implementation's address), then submit a proposal through the multisig to call the proxy's `upgradeTo` or `upgradeToAndCall` function, passing in the new implementation's address.

Thanks, it's a bit more manual than I hoped but it works nonetheless.
