### ISSUE TITLE
Support structs & enums in storage layout checks

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#95]
Checking storage layout that includes structs and enums is not yet supported. The initial version will contain an error that can be turned into a warning.

**Comment by frangio** [comment]
Our current thinking is that we want the plugins to fully check storage compatibility including structs and enums.

**Comment by davidlucid** [comment]
Hey all, any news on this?

**Comment by frangio** [comment]
Hi @davidlucid. We plan to implement full support for checking structs and enums but I can't give you a timeline yet.

Can you share more details about your own project? Are you using the plugins already? Do your contracts have structs, enums, or both?

**Comment by davidlucid** [comment]
Thank you so much! @frangio I am indeed using the Truffle plugin in [`rari-stable-pool-contracts`](https://github.com/Rari-Capital/rari-stable-pool-contracts). I have structs and enums in `RariFundManager` which is deployed via `deployProxy`.
