### ISSUE TITLE
Broken typescript since release upgrades-core@1.31.2

### ISSUE THREAD

**Issue by jmendiola222** [OpenZeppelin/openzeppelin-upgrades#976]
Since release 1.13.2, with this [PR](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/926) we are getting this error while running `tsc` command:

```
node_modules/@openzeppelin/upgrades-core/dist/upgrade-interface-version.d.ts:1:23 - error TS2688: Cannot find type definition file for 'debug'.

1 /// <reference types="debug" />
                        ~~~~~

node_modules/@openzeppelin/upgrades-core/dist/upgrade-interface-version.d.ts:3:110 - error TS7016: Could not find a declaration file for module 'debug'. '~/node_modules/debug/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`

3 export declare function getUpgradeInterfaceVersion(provider: EthereumProvider, address: string, log?: import("debug").Debugger): Promise<string | undefined>;
                                                                                                               ~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@openzeppelin/upgrades-core/dist/upgrade-interface-version.d.ts:1
```

And as this is a not fixed sub-dependency of `"@openzeppelin/hardhat-upgrades": "1.27.0"`, it got updated silently after the release:

![image](https://github.com/OpenZeppelin/openzeppelin-upgrades/assets/5326111/b94794dc-9770-4ead-adb2-cc6505a041a2)

**Comment by ericglau** [comment]
Can you share what version of upgrades-core you currently have installed? e.g. what is the output of `npm list @openzeppelin/upgrades-core`

How are you using the package and when do you see the above error?  If possible, could you share an example github repo that encounters the issue?  Thanks.

**Comment by ericglau** [comment]
I wasn't able to reproduce the issue using the above versions. At this point, having a repo that encounters this issue would be needed to look into this further.

**Comment by ericglau** [comment]
Closing as per the above.  Feel free to reopen if this still occurs.
